
//------------------------------------------------------------------------------
// This file is autogenerated; any modifications might be lost
//------------------------------------------------------------------------------


#include "constantpool.h"
#include "operandstack.h"
#include "jni.h"
#include "instructions.h"
#include "alltests.h"

//------------------------------------------------------------------------------
// Declarations
//------------------------------------------------------------------------------
/* 0x00 */  #define c_nop() 0x00,
/* 0x01 */  #define c_aconst_null() 0x01,
/* 0x02 */  #define c_iconst_m1() 0x02,
/* 0x03 */  #define c_iconst_0() 0x03,
/* 0x04 */  #define c_iconst_1() 0x04,
/* 0x05 */  #define c_iconst_2() 0x05,
/* 0x06 */  #define c_iconst_3() 0x06,
/* 0x07 */  #define c_iconst_4() 0x07,
/* 0x08 */  #define c_iconst_5() 0x08,
/* 0x09 */  #define c_lconst_0() 0x09,
/* 0x0a */  #define c_lconst_1() 0x0a,
/* 0x10 */  #define c_bipush(p1) 0x10, p1,
/* 0x11 */  #define c_sipush(p1, p2) 0x11, p1, p2,
/* 0x12 */  #define c_ldc(p1) 0x12, p1,
/* 0x13 */  #define c_ldc_w(p1, p2) 0x13, p1, p2,
/* 0x14 */  #define c_ldc2_w(p1, p2) 0x14, p1, p2,
/* 0x15 */  #define c_iload(p1) 0x15, p1,
/* 0x16 */  #define c_lload(p1) 0x16, p1,
/* 0x19 */  #define c_aload(p1) 0x19, p1,
/* 0x1a */  #define c_iload_0() 0x1a,
/* 0x1b */  #define c_iload_1() 0x1b,
/* 0x1c */  #define c_iload_2() 0x1c,
/* 0x1d */  #define c_iload_3() 0x1d,
/* 0x1e */  #define c_lload_0() 0x1e,
/* 0x1f */  #define c_lload_1() 0x1f,
/* 0x20 */  #define c_lload_2() 0x20,
/* 0x21 */  #define c_lload_3() 0x21,
/* 0x2a */  #define c_aload_0() 0x2a,
/* 0x2b */  #define c_aload_1() 0x2b,
/* 0x2c */  #define c_aload_2() 0x2c,
/* 0x2d */  #define c_aload_3() 0x2d,
/* 0x2e */  #define c_iaload() 0x2e,
/* 0x2f */  #define c_laload() 0x2f,
/* 0x32 */  #define c_aaload() 0x32,
/* 0x33 */  #define c_baload() 0x33,
/* 0x34 */  #define c_caload() 0x34,
/* 0x36 */  #define c_istore(p1) 0x36, p1,
/* 0x37 */  #define c_lstore(p1) 0x37, p1,
/* 0x3a */  #define c_astore(p1) 0x3a, p1,
/* 0x3b */  #define c_istore_0() 0x3b,
/* 0x3c */  #define c_istore_1() 0x3c,
/* 0x3d */  #define c_istore_2() 0x3d,
/* 0x3e */  #define c_istore_3() 0x3e,
/* 0x3f */  #define c_lstore_0() 0x3f,
/* 0x40 */  #define c_lstore_1() 0x40,
/* 0x41 */  #define c_lstore_2() 0x41,
/* 0x42 */  #define c_lstore_3() 0x42,
/* 0x4b */  #define c_astore_0() 0x4b,
/* 0x4c */  #define c_astore_1() 0x4c,
/* 0x4d */  #define c_astore_2() 0x4d,
/* 0x4e */  #define c_astore_3() 0x4e,
/* 0x4f */  #define c_iastore() 0x4f,
/* 0x50 */  #define c_lastore() 0x50,
/* 0x53 */  #define c_aastore() 0x53,
/* 0x54 */  #define c_bastore() 0x54,
/* 0x55 */  #define c_castore() 0x55,
/* 0x57 */  #define c_pop() 0x57,
/* 0x58 */  #define c_pop2() 0x58,
/* 0x59 */  #define c_dup() 0x59,
/* 0x5a */  #define c_dup_x1() 0x5a,
/* 0x5c */  #define c_dup2() 0x5c,
/* 0x5d */  #define c_dup2_x1() 0x5d,
/* 0x60 */  #define c_iadd() 0x60,
/* 0x61 */  #define c_ladd() 0x61,
/* 0x64 */  #define c_isub() 0x64,
/* 0x65 */  #define c_lsub() 0x65,
/* 0x68 */  #define c_imul() 0x68,
/* 0x69 */  #define c_lmul() 0x69,
/* 0x6c */  #define c_idiv() 0x6c,
/* 0x6d */  #define c_ldiv() 0x6d,
/* 0x70 */  #define c_irem() 0x70,
/* 0x71 */  #define c_lrem() 0x71,
/* 0x74 */  #define c_ineg() 0x74,
/* 0x75 */  #define c_lneg() 0x75,
/* 0x78 */  #define c_ishl() 0x78,
/* 0x79 */  #define c_lshl() 0x79,
/* 0x7a */  #define c_ishr() 0x7a,
/* 0x7b */  #define c_lshr() 0x7b,
/* 0x7d */  #define c_lushr() 0x7d,
/* 0x7e */  #define c_iand() 0x7e,
/* 0x7f */  #define c_land() 0x7f,
/* 0x80 */  #define c_ior() 0x80,
/* 0x81 */  #define c_lor() 0x81,
/* 0x82 */  #define c_ixor() 0x82,
/* 0x83 */  #define c_lxor() 0x83,
/* 0x84 */  #define c_iinc(p1, p2) 0x84, p1, p2,
/* 0x85 */  #define c_i2l() 0x85,
/* 0x88 */  #define c_l2i() 0x88,
/* 0x91 */  #define c_i2b() 0x91,
/* 0x92 */  #define c_i2c() 0x92,
/* 0x94 */  #define c_lcmp() 0x94,
/* 0x99 */  #define c_ifeq(p1, p2) 0x99, p1, p2,
/* 0x9a */  #define c_ifne(p1, p2) 0x9a, p1, p2,
/* 0x9b */  #define c_iflt(p1, p2) 0x9b, p1, p2,
/* 0x9c */  #define c_ifge(p1, p2) 0x9c, p1, p2,
/* 0x9d */  #define c_ifgt(p1, p2) 0x9d, p1, p2,
/* 0x9e */  #define c_ifle(p1, p2) 0x9e, p1, p2,
/* 0x9f */  #define c_if_icmpeq(p1, p2) 0x9f, p1, p2,
/* 0xa0 */  #define c_if_icmpne(p1, p2) 0xa0, p1, p2,
/* 0xa1 */  #define c_if_icmplt(p1, p2) 0xa1, p1, p2,
/* 0xa2 */  #define c_if_icmpge(p1, p2) 0xa2, p1, p2,
/* 0xa3 */  #define c_if_icmpgt(p1, p2) 0xa3, p1, p2,
/* 0xa4 */  #define c_if_icmple(p1, p2) 0xa4, p1, p2,
/* 0xa5 */  #define c_if_acmpeq(p1, p2) 0xa5, p1, p2,
/* 0xa6 */  #define c_if_acmpne(p1, p2) 0xa6, p1, p2,
/* 0xa7 */  #define c_goto(p1, p2) 0xa7, p1, p2,
/* 0xac */  #define c_ireturn() 0xac,
/* 0xad */  #define c_lreturn() 0xad,
/* 0xb0 */  #define c_areturn() 0xb0,
/* 0xb1 */  #define c_vreturn() 0xb1,
/* 0xb2 */  #define c_getstatic(p1, p2) 0xb2, p1, p2,
/* 0xb3 */  #define c_putstatic(p1, p2) 0xb3, p1, p2,
/* 0xb4 */  #define c_getfield(p1, p2) 0xb4, p1, p2,
/* 0xb5 */  #define c_putfield(p1, p2) 0xb5, p1, p2,
/* 0xb6 */  #define c_invokevirtual(p1, p2) 0xb6, p1, p2,
/* 0xb7 */  #define c_invokespecial(p1, p2) 0xb7, p1, p2,
/* 0xb8 */  #define c_invokestatic(p1, p2) 0xb8, p1, p2,
/* 0xb9 */  #define c_invokeinterface(p1, p2, p3, p4) 0xb9, p1, p2, p3, p4,
/* 0xba */  #define c_unused() 0xba,
/* 0xbb */  #define c_new(p1, p2) 0xbb, p1, p2,
/* 0xbc */  #define c_newarray(p1) 0xbc, p1,
/* 0xbd */  #define c_anewarray(p1, p2) 0xbd, p1, p2,
/* 0xbe */  #define c_arraylength() 0xbe,
/* 0xbf */  #define c_athrow() 0xbf,
/* 0xc0 */  #define c_checkcast(p1, p2) 0xc0, p1, p2,
/* 0xc1 */  #define c_instanceof(p1, p2) 0xc1, p1, p2,
/* 0xc2 */  #define c_monitorenter() 0xc2,
/* 0xc3 */  #define c_monitorexit() 0xc3,
/* 0xc6 */  #define c_ifnull(p1, p2) 0xc6, p1, p2,
/* 0xc7 */  #define c_ifnonnull(p1, p2) 0xc7, p1, p2,

// The total number of instructions implemented by thinJ so far: 130

//------------------------------------------------------------------------------
// Class Instance Information
//------------------------------------------------------------------------------


const classInstanceInfoDef const allClassInstanceInfo[] = {
    {   0,   1,   0,   0, CT_CLASS,          0, 0               }, // 0:java/lang/Object
    {   0,   1,   0,   0, CT_BYTE_ARRAY,     0, sizeof(jbyte)   }, // 1:[B
    {   0,   1,   0,   0, CT_CHAR_ARRAY,     0, sizeof(jchar)   }, // 2:[C
    {   0,   1,   0,   0, CT_INT_ARRAY,      0, sizeof(jint)    }, // 3:[I
    {   0,   1,   0,   0, CT_LONG_ARRAY,     0, sizeof(jlong)   }, // 4:[J
    {   0,   1,   0,   0, CT_OBJECT_ARRAY,  10, sizeof(jobject) }, // 5:[Ljava/lang/Class
    {   0,   1,   0,   0, CT_OBJECT_ARRAY,   0, sizeof(jobject) }, // 6:[Ljava/lang/Object
    {   0,   1,   0,   0, CT_CLASS,          0, 0               }, // 7:java/io/PrintStream
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 8:java/lang/ArithmeticException
    {  15,   3,   0,   0, CT_CLASS,          0, 0               }, // 9:java/lang/ArrayIndexOutOfBoundsException
    {   0,   2,   0,   0, CT_CLASS,          0, 0               }, // 10:java/lang/Class
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 11:java/lang/ClassCastException
    {  28,   3,   0,   0, CT_CLASS,          0, 0               }, // 12:java/lang/Error
    {  28,   3,   0,   0, CT_CLASS,          0, 0               }, // 13:java/lang/Exception
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 14:java/lang/IllegalMonitorStateException
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 15:java/lang/IndexOutOfBoundsException
    {  13,   3,   0,   0, CT_CLASS,          0, 0               }, // 16:java/lang/InterruptedException
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 17:java/lang/NegativeArraySizeException
    {  23,   3,   0,   0, CT_CLASS,          0, 0               }, // 18:java/lang/NullPointerException
    {   0,   4,   0,   0, CT_CLASS,          0, 0               }, // 19:java/lang/Object$Monitor
    {   0,   3,   0,   0, CT_CLASS,          0, 0               }, // 20:java/lang/Object$WaitElement
    {  29,   3,   0,   0, CT_CLASS,          0, 0               }, // 21:java/lang/OutOfMemoryError
    {   0,   1,   0,   0, CT_INTERFACE,      0, 0               }, // 22:java/lang/Runnable
    {  13,   3,   0,   0, CT_CLASS,          0, 0               }, // 23:java/lang/RuntimeException
    {   0,   2,   0,   0, CT_CLASS,          0, 0               }, // 24:java/lang/String
    {   0,   2,   0,   0, CT_CLASS,          0, 0               }, // 25:java/lang/StringBuilder
    {   0,   1,   0,   0, CT_CLASS,          0, 0               }, // 26:java/lang/System
    {   0,  10,   0,   1, CT_CLASS,          0, 0               }, // 27:java/lang/Thread
    {   0,   3,   1,   0, CT_CLASS,          0, 0               }, // 28:java/lang/Throwable
    {  12,   3,   1,   0, CT_CLASS,          0, 0               }, // 29:java/lang/VirtualMachineError
    {   0,   1,   1,   0, CT_CLASS,          0, 0               }, // 30:java/util/Arrays
    {   0,   1,   1,   0, CT_CLASS,          0, 0               }, // 31:thinj/regression/AllTests
    {   0,   1,   1,   0, CT_CLASS,          0, 0               }, // 32:thinj/regression/ThreadTest
    {   0,   2,   1,   0, CT_CLASS,          0, 0               }, // 33:thinj/util/SimpleList
    {   0,   3,   1,   0, CT_CLASS,          0, 0               }, // 34:thinj/util/SimpleList$Element
};
const u2 cpNumberOfAllClassInstanceInfo = 35;

//------------------------------------------------------------------------------
// Implemented interfaces
//------------------------------------------------------------------------------

const u2 const implementedInterfaces[] = {
    // java/lang/Thread
    22, 
};

//------------------------------------------------------------------------------
// Class References
//------------------------------------------------------------------------------

const classReference const allClassReferences[] = {
    // Class Id: 0
    {0, 2, 25}, // "java/lang/StringBuilder"
    // Class Id: 7
    {7, 9, 25}, // "java/lang/StringBuilder"
    // Class Id: 9
    {9, 2, 25}, // "java/lang/StringBuilder"
    // Class Id: 10
    {10, 2, 25}, // "java/lang/StringBuilder"
    // Class Id: 21
    {21, 4, 21}, // "java/lang/OutOfMemoryError"
    // Class Id: 25
    {25, 10, 24}, // "java/lang/String"
    // Class Id: 26
    {26, 2, 7}, // "java/io/PrintStream"
    // Class Id: 27
    {27, 19, 28}, // "java/lang/Throwable"
    {27, 23, 27}, // "java/lang/Thread"
    // Class Id: 28
    {28, 10, 25}, // "java/lang/StringBuilder"
    // Class Id: 32
    {32, 15, 25}, // "java/lang/StringBuilder"
    {32, 30, 0}, // "java/lang/Object"
};
const u2 numberOfAllClassReferences = 12;

//------------------------------------------------------------------------------
// Class referenced by VM
//------------------------------------------------------------------------------


const u2 C_java_lang_ArithmeticException = 8;
const u2 C_java_lang_ArrayIndexOutOfBoundsException = 9;
const u2 C_java_lang_Class = 10;
const u2 C_java_lang_ClassCastException = 11;
const u2 C_java_lang_IllegalMonitorStateException = 14;
const u2 C_java_lang_InterruptedException = 16;
const u2 C_java_lang_NegativeArraySizeException = 17;
const u2 C_java_lang_NullPointerException = 18;
const u2 C_java_lang_Object = 0;
const u2 C_java_lang_Object_Monitor = 19;
const u2 C_java_lang_Object_WaitElement = 20;
const u2 C_java_lang_OutOfMemoryError = 21;
const u2 C_java_lang_String = 24;
const u2 C_java_lang_Thread = 27;
const u2 C_thinj_util_SimpleList = 33;
const u2 C_thinj_util_SimpleList_Element = 34;

//------------------------------------------------------------------------------
// Link Ids referenced by VM
//------------------------------------------------------------------------------


const u2 M_java_lang_ArithmeticException__init_Ljava_lang_String = 24;
const u2 M_java_lang_ArrayIndexOutOfBoundsException__init_I = 25;
const u2 A_java_lang_Class_aAllClasses = 22;
const u2 A_java_lang_Class_aClassId = 21;
const u2 A_java_lang_Class_aGlobalRefList = 23;
const u2 M_java_lang_ClassCastException__init = 1;
const u2 M_java_lang_IllegalMonitorStateException__init_Ljava_lang_String = 24;
const u2 M_java_lang_InterruptedException__init = 1;
const u2 M_java_lang_NegativeArraySizeException__init = 1;
const u2 M_java_lang_NullPointerException__init = 1;
const u2 A_java_lang_Object_aMonitor = 0;
const u2 A_java_lang_Object_Monitor_aLockCount = 40;
const u2 A_java_lang_Object_Monitor_aOwner = 39;
const u2 A_java_lang_Object_Monitor_aWaitSet = 41;
const u2 A_java_lang_Object_WaitElement_aNext = 43;
const u2 A_java_lang_Object_WaitElement_aWaiting = 42;
const u2 M_java_lang_OutOfMemoryError__init = 1;
const u2 M_java_lang_OutOfMemoryError_getInstance = 27;
const u2 A_java_lang_String_value = 5;
const u2 A_java_lang_Thread_aBlockingObject = 60;
const u2 A_java_lang_Thread_aCurrentThread = 53;
const u2 A_java_lang_Thread_aId = 48;
const u2 A_java_lang_Thread_aInterrupted = 50;
const u2 A_java_lang_Thread_aLockCount = 40;
const u2 A_java_lang_Thread_aState = 49;
const u2 A_java_lang_Thread_aWakeUpAt = 61;
const u2 M_java_lang_Thread_runFromNative = 63;
const u2 A_thinj_util_SimpleList_aList = 68;
const u2 A_thinj_util_SimpleList_Element_aNext = 69;
const u2 A_thinj_util_SimpleList_Element_aValue = 70;

//------------------------------------------------------------------------------
// Field references
//------------------------------------------------------------------------------

const memberReference const allFieldReferences10[] = {
    {10, 21}, // 0: java/lang/Class#aClassId#I
};

const memberReference const allFieldReferences21[] = {
    {21, 26}, // 0: java/lang/OutOfMemoryError#INSTANCE#Ljava/lang/OutOfMemoryError;
};

const memberReference const allFieldReferences24[] = {
    {24, 5}, // 0: java/lang/String#value#[C
};

const memberReference const allFieldReferences25[] = {
    {25, 122}, // 0: java/lang/StringBuilder#aValue#[C
};

const memberReference const allFieldReferences26[] = {
    {26, 71}, // 0: java/lang/System#out#Ljava/io/PrintStream;
    {26, 33}, // 1: java/lang/System#err#Ljava/io/PrintStream;
};

const memberReference const allFieldReferences27[] = {
    {27, 46}, // 0: java/lang/Thread#aRunnable#Ljava/lang/Runnable;
    {27, 47}, // 1: java/lang/Thread#aThreadIdGenerator#J
    {27, 48}, // 2: java/lang/Thread#aId#J
    {27, 49}, // 3: java/lang/Thread#aState#I
    {27, 50}, // 4: java/lang/Thread#aInterrupted#Z
    {27, 53}, // 5: java/lang/Thread#aCurrentThread#Ljava/lang/Thread;
};

const memberReference const allFieldReferences28[] = {
    {28, 29}, // 0: java/lang/Throwable#aCause#Ljava/lang/String;
    {28, 31}, // 1: java/lang/Throwable#aStackTrace#[I
    {26, 33}, // 2: java/lang/System#err#Ljava/io/PrintStream;
};

const memberReference const allFieldReferences31[] = {
    {26, 71}, // 0: java/lang/System#out#Ljava/io/PrintStream;
};

const memberReference const allFieldReferences32[] = {
    {32, 85}, // 0: thinj/regression/ThreadTest#aFlag#Z
    {32, 87}, // 1: thinj/regression/ThreadTest#aMutex#Ljava/lang/Object;
    {32, 88}, // 2: thinj/regression/ThreadTest#aCount1#I
    {32, 90}, // 3: thinj/regression/ThreadTest#aDone#Z
    {26, 71}, // 4: java/lang/System#out#Ljava/io/PrintStream;
};


//------------------------------------------------------------------------------
// Field properties
//------------------------------------------------------------------------------

const fieldInClass const allFields0[] = {
   {0, 0, 1}, // 0-java/lang/Object#aMonitor#Ljava/lang/Object$Monitor;
};

const fieldInClass const allFields10[] = {
   {21, 1, 1}, // 21-java/lang/Class#aClassId#I
   {22, 0, 1}, // 22-java/lang/Class#aAllClasses#[Ljava/lang/Class;
   {23, 1, 1}, // 23-java/lang/Class#aGlobalRefList#Ljava/lang/Object;
};

const fieldInClass const allFields19[] = {
   {39, 1, 1}, // 39-java/lang/Object$Monitor#aOwner#Ljava/lang/Thread;
   {40, 2, 1}, // 40-java/lang/Object$Monitor#aLockCount#I
   {41, 3, 1}, // 41-java/lang/Object$Monitor#aWaitSet#Ljava/lang/Object$WaitElement;
};

const fieldInClass const allFields20[] = {
   {42, 1, 1}, // 42-java/lang/Object$WaitElement#aWaiting#Ljava/lang/Thread;
   {43, 2, 1}, // 43-java/lang/Object$WaitElement#aNext#Ljava/lang/Object$WaitElement;
};

const fieldInClass const allFields21[] = {
   {26, 2, 1}, // 26-java/lang/OutOfMemoryError#INSTANCE#Ljava/lang/OutOfMemoryError;
};

const fieldInClass const allFields24[] = {
   {5, 1, 1}, // 5-java/lang/String#value#[C
};

const fieldInClass const allFields25[] = {
   {122, 1, 1}, // 122-java/lang/StringBuilder#aValue#[C
};

const fieldInClass const allFields26[] = {
   {33, 7, 1}, // 33-java/lang/System#err#Ljava/io/PrintStream;
   {71, 6, 1}, // 71-java/lang/System#out#Ljava/io/PrintStream;
};

const fieldInClass const allFields27[] = {
   {40, 6, 1}, // 40-java/lang/Thread#aLockCount#I
   {46, 3, 1}, // 46-java/lang/Thread#aRunnable#Ljava/lang/Runnable;
   {47, 4, 2}, // 47-java/lang/Thread#aThreadIdGenerator#J
   {48, 1, 2}, // 48-java/lang/Thread#aId#J
   {49, 4, 1}, // 49-java/lang/Thread#aState#I
   {50, 9, 1}, // 50-java/lang/Thread#aInterrupted#Z
   {53, 3, 1}, // 53-java/lang/Thread#aCurrentThread#Ljava/lang/Thread;
   {60, 5, 1}, // 60-java/lang/Thread#aBlockingObject#Ljava/lang/Object;
   {61, 7, 2}, // 61-java/lang/Thread#aWakeUpAt#J
};

const fieldInClass const allFields28[] = {
   {29, 1, 1}, // 29-java/lang/Throwable#aCause#Ljava/lang/String;
   {31, 2, 1}, // 31-java/lang/Throwable#aStackTrace#[I
};

const fieldInClass const allFields32[] = {
   {85, 9, 1}, // 85-thinj/regression/ThreadTest#aFlag#Z
   {87, 11, 1}, // 87-thinj/regression/ThreadTest#aMutex#Ljava/lang/Object;
   {88, 10, 1}, // 88-thinj/regression/ThreadTest#aCount1#I
   {90, 8, 1}, // 90-thinj/regression/ThreadTest#aDone#Z
};

const fieldInClass const allFields33[] = {
   {68, 1, 1}, // 68-thinj/util/SimpleList#aList#Lthinj/util/SimpleList$Element;
};

const fieldInClass const allFields34[] = {
   {69, 1, 1}, // 69-thinj/util/SimpleList$Element#aNext#Lthinj/util/SimpleList$Element;
   {70, 2, 1}, // 70-thinj/util/SimpleList$Element#aValue#Ljava/lang/Object;
};


//------------------------------------------------------------------------------
// Static Memory
//------------------------------------------------------------------------------

const int staticMemorySize = 12;
stackable staticMemory[12];

//------------------------------------------------------------------------------
// Method References
//------------------------------------------------------------------------------

const memberReference const allMethodReferences0[] = {
    {25, 1, 1}, // 0: java/lang/StringBuilder#<init>#()V
    {0, 2, 1}, // 1: java/lang/Object#getClass#()Ljava/lang/Class;
    {10, 3, 1}, // 2: java/lang/Class#getName#()Ljava/lang/String;
    {25, 4, 2}, // 3: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {0, 15, 1}, // 4: java/lang/Object#hashCode#()I
    {25, 17, 2}, // 5: java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 6: java/lang/StringBuilder#toString#()Ljava/lang/String;
};

const memberReference const allMethodReferences7[] = {
    {0, 1, 1}, // 0: java/lang/Object#<init>#()V
    {7, 75, 1}, // 1: java/io/PrintStream#outStringLf#(Ljava/lang/String;)V
    {7, 76, 1}, // 2: java/io/PrintStream#outString#(Ljava/lang/String;)V
    {7, 36, 2}, // 3: java/io/PrintStream#print#(Ljava/lang/String;)V
    {25, 1, 1}, // 4: java/lang/StringBuilder#<init>#()V
    {25, 4, 2}, // 5: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 17, 2}, // 6: java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 7: java/lang/StringBuilder#toString#()Ljava/lang/String;
    {0, 6, 1}, // 8: java/lang/Object#toString#()Ljava/lang/String;
};

const memberReference const allMethodReferences8[] = {
    {23, 24, 2}, // 0: java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
};

const memberReference const allMethodReferences9[] = {
    {15, 24, 2}, // 0: java/lang/IndexOutOfBoundsException#<init>#(Ljava/lang/String;)V
    {25, 1, 1}, // 1: java/lang/StringBuilder#<init>#()V
    {25, 4, 2}, // 2: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 17, 2}, // 3: java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 4: java/lang/StringBuilder#toString#()Ljava/lang/String;
};

const memberReference const allMethodReferences10[] = {
    {25, 1, 1}, // 0: java/lang/StringBuilder#<init>#()V
    {25, 4, 2}, // 1: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 17, 2}, // 2: java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 3: java/lang/StringBuilder#toString#()Ljava/lang/String;
    {10, 3, 1}, // 4: java/lang/Class#getName#()Ljava/lang/String;
};

const memberReference const allMethodReferences11[] = {
    {23, 1, 1}, // 0: java/lang/RuntimeException#<init>#()V
};

const memberReference const allMethodReferences12[] = {
    {28, 1, 1}, // 0: java/lang/Throwable#<init>#()V
};

const memberReference const allMethodReferences13[] = {
    {28, 24, 2}, // 0: java/lang/Throwable#<init>#(Ljava/lang/String;)V
    {28, 1, 1}, // 1: java/lang/Throwable#<init>#()V
};

const memberReference const allMethodReferences14[] = {
    {23, 24, 2}, // 0: java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
};

const memberReference const allMethodReferences15[] = {
    {23, 24, 2}, // 0: java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
};

const memberReference const allMethodReferences16[] = {
    {13, 1, 1}, // 0: java/lang/Exception#<init>#()V
};

const memberReference const allMethodReferences17[] = {
    {23, 1, 1}, // 0: java/lang/RuntimeException#<init>#()V
};

const memberReference const allMethodReferences18[] = {
    {23, 24, 2}, // 0: java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
    {18, 24, 2}, // 1: java/lang/NullPointerException#<init>#(Ljava/lang/String;)V
};

const memberReference const allMethodReferences21[] = {
    {29, 1, 1}, // 0: java/lang/VirtualMachineError#<init>#()V
    {21, 1, 1}, // 1: java/lang/OutOfMemoryError#<init>#()V
};

const memberReference const allMethodReferences23[] = {
    {13, 24, 2}, // 0: java/lang/Exception#<init>#(Ljava/lang/String;)V
    {13, 1, 1}, // 1: java/lang/Exception#<init>#()V
};

const memberReference const allMethodReferences24[] = {
    {0, 1, 1}, // 0: java/lang/Object#<init>#()V
    {30, 7, 1}, // 1: java/util/Arrays#hashCode#([C)I
};

const memberReference const allMethodReferences25[] = {
    {0, 1, 1}, // 0: java/lang/Object#<init>#()V
    {24, 11, 1}, // 1: java/lang/String#length#()I
    {24, 14, 5}, // 2: java/lang/String#getChars#(II[CI)V
    {25, 4, 2}, // 3: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {24, 9, 4}, // 4: java/lang/String#<init>#([CII)V
    {24, 10, 2}, // 5: java/lang/String#<init>#([C)V
};

const memberReference const allMethodReferences26[] = {
    {7, 1, 1}, // 0: java/io/PrintStream#<init>#()V
};

const memberReference const allMethodReferences27[] = {
    {27, 45, 2}, // 0: java/lang/Thread#<init>#(Ljava/lang/Runnable;)V
    {0, 1, 1}, // 1: java/lang/Object#<init>#()V
    {27, 51, 1}, // 2: java/lang/Thread#attach#()V
    {22, 44, 1}, // 3: java/lang/Runnable#run#()V
    {27, 44, 1}, // 4: java/lang/Thread#run#()V
    {28, 38, 1}, // 5: java/lang/Throwable#printStackTrace#()V
    {27, 52, 0}, // 6: java/lang/Thread#yield#()V
    {27, 1, 1}, // 7: java/lang/Thread#<init>#()V
};

const memberReference const allMethodReferences28[] = {
    {28, 24, 2}, // 0: java/lang/Throwable#<init>#(Ljava/lang/String;)V
    {0, 1, 1}, // 1: java/lang/Object#<init>#()V
    {28, 30, 1}, // 2: java/lang/Throwable#getStackTraceDepth#()I
    {28, 32, 2}, // 3: java/lang/Throwable#getStackTraceElement#(I)I
    {0, 2, 1}, // 4: java/lang/Object#getClass#()Ljava/lang/Class;
    {7, 34, 2}, // 5: java/io/PrintStream#print#(Ljava/lang/Object;)V
    {25, 1, 1}, // 6: java/lang/StringBuilder#<init>#()V
    {25, 4, 2}, // 7: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 8: java/lang/StringBuilder#toString#()Ljava/lang/String;
    {7, 35, 2}, // 9: java/io/PrintStream#println#(Ljava/lang/String;)V
    {7, 36, 2}, // 10: java/io/PrintStream#print#(Ljava/lang/String;)V
    {7, 37, 2}, // 11: java/io/PrintStream#print#(I)V
};

const memberReference const allMethodReferences29[] = {
    {12, 1, 1}, // 0: java/lang/Error#<init>#()V
};

const memberReference const allMethodReferences31[] = {
    {7, 35, 2}, // 0: java/io/PrintStream#println#(Ljava/lang/String;)V
    {32, 72, 1}, // 1: thinj/regression/ThreadTest#main#([Ljava/lang/String;)V
    {21, 28, 0}, // 2: java/lang/OutOfMemoryError#<clinit>#()V
    {26, 28, 0}, // 3: java/lang/System#<clinit>#()V
    {27, 28, 0}, // 4: java/lang/Thread#<clinit>#()V
    {32, 28, 0}, // 5: thinj/regression/ThreadTest#<clinit>#()V
    {31, 72, 1}, // 6: thinj/regression/AllTests#main#([Ljava/lang/String;)V
};

const memberReference const allMethodReferences32[] = {
    {0, 1, 1}, // 0: java/lang/Object#<init>#()V
    {7, 35, 2}, // 1: java/io/PrintStream#println#(Ljava/lang/String;)V
    {32, 91, 0}, // 2: thinj/regression/ThreadTest#simpleYield#()V
    {32, 92, 0}, // 3: thinj/regression/ThreadTest#yieldAndGC#()V
    {27, 52, 0}, // 4: java/lang/Thread#yield#()V
    {25, 1, 1}, // 5: java/lang/StringBuilder#<init>#()V
    {25, 4, 2}, // 6: java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 17, 2}, // 7: java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    {25, 6, 1}, // 8: java/lang/StringBuilder#toString#()Ljava/lang/String;
};


//------------------------------------------------------------------------------
// Method Attributes
//------------------------------------------------------------------------------


const methodInClass const allMethods0[] = {
    {0, 1, 0x0085, 1, 1, 1, 0}, // 1-java/lang/Object#<init>#()V
    {0, 2, 0x0086, 0, 1, 1, 2}, // 2-java/lang/Object#getClass#()Ljava/lang/Class;
    {0, 6, 0x0086, 33, 1, 1, 0}, // 6-java/lang/Object#toString#()Ljava/lang/String;
    {0, 15, 0x0086, 0, 1, 1, 1}, // 15-java/lang/Object#hashCode#()I
};

const methodInClass const allMethods7[] = {
    {7, 1, 0x0275, 5, 1, 1, 0}, // 1-java/io/PrintStream#<init>#()V
    {7, 34, 0x029c, 17, 2, 2, 0}, // 34-java/io/PrintStream#print#(Ljava/lang/Object;)V
    {7, 35, 0x027a, 5, 2, 2, 0}, // 35-java/io/PrintStream#println#(Ljava/lang/String;)V
    {7, 36, 0x027f, 5, 2, 2, 0}, // 36-java/io/PrintStream#print#(Ljava/lang/String;)V
    {7, 37, 0x0284, 24, 2, 2, 0}, // 37-java/io/PrintStream#print#(I)V
    {7, 75, 0x027a, 0, 1, 1, 7}, // 75-java/io/PrintStream#outStringLf#(Ljava/lang/String;)V
    {7, 76, 0x027a, 0, 1, 1, 8}, // 76-java/io/PrintStream#outString#(Ljava/lang/String;)V
};

const methodInClass const allMethods8[] = {
    {8, 24, 0x00db, 6, 2, 2, 0}, // 24-java/lang/ArithmeticException#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods9[] = {
    {9, 25, 0x00c3, 24, 2, 2, 0}, // 25-java/lang/ArrayIndexOutOfBoundsException#<init>#(I)V
};

const methodInClass const allMethods10[] = {
    {10, 3, 0x00a7, 23, 1, 1, 0}, // 3-java/lang/Class#getName#()Ljava/lang/String;
    {10, 6, 0x00be, 5, 1, 1, 0}, // 6-java/lang/Class#toString#()Ljava/lang/String;
};

const methodInClass const allMethods11[] = {
    {11, 1, 0x00e1, 5, 1, 1, 0}, // 1-java/lang/ClassCastException#<init>#()V
};

const methodInClass const allMethods12[] = {
    {12, 1, 0x011b, 5, 1, 1, 0}, // 1-java/lang/Error#<init>#()V
};

const methodInClass const allMethods13[] = {
    {13, 1, 0x03ec, 5, 1, 1, 0}, // 1-java/lang/Exception#<init>#()V
    {13, 24, 0x03e6, 6, 2, 2, 0}, // 24-java/lang/Exception#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods14[] = {
    {14, 24, 0x00e6, 6, 2, 2, 0}, // 24-java/lang/IllegalMonitorStateException#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods15[] = {
    {15, 24, 0x03f1, 6, 2, 2, 0}, // 24-java/lang/IndexOutOfBoundsException#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods16[] = {
    {16, 1, 0x00ec, 5, 1, 1, 0}, // 1-java/lang/InterruptedException#<init>#()V
};

const methodInClass const allMethods17[] = {
    {17, 1, 0x00f1, 5, 1, 1, 0}, // 1-java/lang/NegativeArraySizeException#<init>#()V
};

const methodInClass const allMethods18[] = {
    {18, 1, 0x00fc, 6, 1, 1, 0}, // 1-java/lang/NullPointerException#<init>#()V
    {18, 24, 0x00f6, 6, 2, 2, 0}, // 24-java/lang/NullPointerException#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods21[] = {
    {21, 1, 0x0102, 5, 1, 1, 0}, // 1-java/lang/OutOfMemoryError#<init>#()V
    {21, 27, 0x0107, 4, 0, 0, 0}, // 27-java/lang/OutOfMemoryError#getInstance#()Ljava/lang/OutOfMemoryError;
    {21, 28, 0x010b, 11, 0, 0, 0}, // 28-java/lang/OutOfMemoryError#<clinit>#()V
};

const methodInClass const allMethods22[] = {
    {22, 44, 0x01e6, 0, 0, 1, 0}, // 44-java/lang/Runnable#run#()V
};

const methodInClass const allMethods23[] = {
    {23, 1, 0x03e1, 5, 1, 1, 0}, // 1-java/lang/RuntimeException#<init>#()V
    {23, 24, 0x03db, 6, 2, 2, 0}, // 24-java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
};

const methodInClass const allMethods24[] = {
    {24, 6, 0x0072, 2, 1, 1, 0}, // 6-java/lang/String#toString#()Ljava/lang/String;
    {24, 9, 0x0000, 40, 5, 4, 0}, // 9-java/lang/String#<init>#([CII)V
    {24, 10, 0x0028, 36, 3, 2, 0}, // 10-java/lang/String#<init>#([C)V
    {24, 11, 0x004c, 6, 1, 1, 0}, // 11-java/lang/String#length#()I
    {24, 14, 0x0052, 32, 6, 5, 0}, // 14-java/lang/String#getChars#(II[CI)V
    {24, 15, 0x0074, 17, 3, 1, 0}, // 15-java/lang/String#hashCode#()I
};

const methodInClass const allMethods25[] = {
    {25, 1, 0x0326, 12, 1, 1, 0}, // 1-java/lang/StringBuilder#<init>#()V
    {25, 4, 0x0332, 72, 4, 2, 0}, // 4-java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    {25, 6, 0x03cf, 12, 1, 1, 0}, // 6-java/lang/StringBuilder#toString#()Ljava/lang/String;
    {25, 17, 0x037a, 85, 5, 2, 0}, // 17-java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
};

const methodInClass const allMethods26[] = {
    {26, 28, 0x0260, 21, 0, 0, 0}, // 28-java/lang/System#<clinit>#()V
};

const methodInClass const allMethods27[] = {
    {27, 1, 0x01e6, 6, 1, 1, 0}, // 1-java/lang/Thread#<init>#()V
    {27, 28, 0x0236, 21, 0, 0, 0}, // 28-java/lang/Thread#<clinit>#()V
    {27, 44, 0x0235, 1, 1, 1, 0}, // 44-java/lang/Thread#run#()V
    {27, 45, 0x01ec, 33, 2, 2, 0}, // 45-java/lang/Thread#<init>#(Ljava/lang/Runnable;)V
    {27, 51, 0x0236, 0, 1, 1, 6}, // 51-java/lang/Thread#attach#()V
    {27, 52, 0x0236, 0, 0, 0, 5}, // 52-java/lang/Thread#yield#()V
    {27, 63, 0x020d, 40, 2, 1, 0}, // 63-java/lang/Thread#runFromNative#()V
};

const methodInClass const allMethods28[] = {
    {28, 1, 0x0120, 6, 1, 1, 0}, // 1-java/lang/Throwable#<init>#()V
    {28, 6, 0x01cf, 23, 1, 1, 0}, // 6-java/lang/Throwable#toString#()Ljava/lang/String;
    {28, 24, 0x0126, 46, 4, 2, 0}, // 24-java/lang/Throwable#<init>#(Ljava/lang/String;)V
    {28, 30, 0x0154, 0, 1, 1, 4}, // 30-java/lang/Throwable#getStackTraceDepth#()I
    {28, 32, 0x0154, 0, 2, 2, 3}, // 32-java/lang/Throwable#getStackTraceElement#(I)I
    {28, 38, 0x0154, 123, 6, 1, 0}, // 38-java/lang/Throwable#printStackTrace#()V
};

const methodInClass const allMethods29[] = {
    {29, 1, 0x0116, 5, 1, 1, 0}, // 1-java/lang/VirtualMachineError#<init>#()V
};

const methodInClass const allMethods30[] = {
    {30, 7, 0x03f7, 38, 6, 1, 0}, // 7-java/util/Arrays#hashCode#([C)I
};

const methodInClass const allMethods31[] = {
    {31, 72, 0x024b, 21, 1, 1, 0}, // 72-thinj/regression/AllTests#main#([Ljava/lang/String;)V
    {31, 124, 0x041d, 16, 0, 0, 0}, // 124-thinj/regression/AllTests#<jvminit>#()V
};

const methodInClass const allMethods32[] = {
    {32, 28, 0x030f, 23, 0, 0, 0}, // 28-thinj/regression/ThreadTest#<clinit>#()V
    {32, 72, 0x02ad, 23, 1, 1, 0}, // 72-thinj/regression/ThreadTest#main#([Ljava/lang/String;)V
    {32, 91, 0x02c4, 22, 1, 0, 0}, // 91-thinj/regression/ThreadTest#simpleYield#()V
    {32, 92, 0x02da, 53, 2, 0, 0}, // 92-thinj/regression/ThreadTest#yieldAndGC#()V
};


//------------------------------------------------------------------------------
// Exception Handlers
//------------------------------------------------------------------------------

const exceptionHandler const allExceptionHandersInAllClasses[] = {
    {27, 28, 0x020d, 0x0224, 0x0227}, // java/lang/Throwable @0x020d
};
const u2 numberOfAllExceptionHandersInAllClasses = 1;

//------------------------------------------------------------------------------
// Native Method Encapsulations
//------------------------------------------------------------------------------

// 1: Java_java_lang_Object_hashCode
JNIEXPORT jint JNICALL Java_java_lang_Object_hashCode(JNIEnv *, jobject);
void native1(contextDef* context) {

    jobject thisOrClass = operandStackPeekObjectRef(context, 0);
    jint retval = Java_java_lang_Object_hashCode(context, thisOrClass);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        operandStackPushJavaInt(context, retval);
    }
}
// 2: Java_java_lang_Object_getClass
JNIEXPORT jobject JNICALL Java_java_lang_Object_getClass(JNIEnv *, jobject);
void native2(contextDef* context) {

    jobject thisOrClass = operandStackPeekObjectRef(context, 0);
    jobject retval = Java_java_lang_Object_getClass(context, thisOrClass);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        operandStackPushObjectRef(context, retval);
    }
}
// 3: Java_java_lang_Throwable_getStackTraceElement
JNIEXPORT jint JNICALL Java_java_lang_Throwable_getStackTraceElement(JNIEnv *, jobject, jint);
void native3(contextDef* context) {
    jint p0 = operandStackPeekJavaInt(context, 1);

    jobject thisOrClass = operandStackPeekObjectRef(context, 0);
    jint retval = Java_java_lang_Throwable_getStackTraceElement(context, thisOrClass, p0);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        operandStackPushJavaInt(context, retval);
    }
}
// 4: Java_java_lang_Throwable_getStackTraceDepth
JNIEXPORT jint JNICALL Java_java_lang_Throwable_getStackTraceDepth(JNIEnv *, jobject);
void native4(contextDef* context) {

    jobject thisOrClass = operandStackPeekObjectRef(context, 0);
    jint retval = Java_java_lang_Throwable_getStackTraceDepth(context, thisOrClass);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        operandStackPushJavaInt(context, retval);
    }
}
// 5: Java_java_lang_Thread_yield
JNIEXPORT void JNICALL Java_java_lang_Thread_yield(JNIEnv *, jclass);
void native5(contextDef* context) {

    jclass thisOrClass = getJavaLangClass(context, 27);
    Java_java_lang_Thread_yield(context, thisOrClass);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        
    }
}
// 6: Java_java_lang_Thread_attach
JNIEXPORT void JNICALL Java_java_lang_Thread_attach(JNIEnv *, jobject);
void native6(contextDef* context) {

    jobject thisOrClass = operandStackPeekObjectRef(context, 0);
    Java_java_lang_Thread_attach(context, thisOrClass);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        
    }
}
// 7: Java_java_io_PrintStream_outStringLf
JNIEXPORT void JNICALL Java_java_io_PrintStream_outStringLf(JNIEnv *, jclass, jstring);
void native7(contextDef* context) {
    jstring p0 = (jstring) operandStackPeekObjectRef(context, 0);

    jclass thisOrClass = getJavaLangClass(context, 7);
    Java_java_io_PrintStream_outStringLf(context, thisOrClass, p0);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        
    }
}
// 8: Java_java_io_PrintStream_outString
JNIEXPORT void JNICALL Java_java_io_PrintStream_outString(JNIEnv *, jclass, jstring);
void native8(contextDef* context) {
    jstring p0 = (jstring) operandStackPeekObjectRef(context, 0);

    jclass thisOrClass = getJavaLangClass(context, 7);
    Java_java_io_PrintStream_outString(context, thisOrClass, p0);
    if (!ExceptionCheck(context)) {
        pop_frame(context);
        
    }
}

//------------------------------------------------------------------------------
// Native Method Jump Table
//------------------------------------------------------------------------------

const nativeJumpTableEntry const nativeJumpTable[] = {
    native1,
    native2,
    native3,
    native4,
    native5,
    native6,
    native7,
    native8,
};
const u2 nativeJumpTableSize = 8;

//------------------------------------------------------------------------------
// Integer Constant References
//------------------------------------------------------------------------------

const u2 numberOfAllIntegerConstantReferences = 0;
const integerConstantReference const allIntegerConstantReferences[] = {
};

//------------------------------------------------------------------------------
// Long Constant References
//------------------------------------------------------------------------------

const u2 numberOfAllLongConstantReferences = 0;
const longConstantReference const allLongConstantReferences[] = {
};

//------------------------------------------------------------------------------
// Float Constant References
//------------------------------------------------------------------------------

const u2 numberOfAllFloatConstantReferences = 0;
const floatConstantReference const allFloatConstantReferences[] = {
};

//------------------------------------------------------------------------------
// Double Constant References
//------------------------------------------------------------------------------

const u2 numberOfAllDoubleConstantReferences = 0;
const doubleConstantReference const allDoubleConstantReferences[] = {
};

//------------------------------------------------------------------------------
// String Constant References
//------------------------------------------------------------------------------

const u2 numberOfAllStringConstantReferences = 16;
const stringConstantReference const allStringConstantReferences[] = {
    {0, 7, "@"}, 
    {10, 4, "#"}, 
    {9, 4, "Index out of bounds: "}, 
    {28, 12, ": "}, 
    {28, 15, ""}, 
    {28, 17, ","}, 
    {28, 19, "  at: "}, 
    {28, 21, "Throwable: "}, 
    {31, 3, "Starting"}, 
    {31, 5, "Test 28"}, 
    {7, 4, ""}, 
    {7, 17, "null"}, 
    {32, 9, "Hello folks"}, 
    {32, 13, "Bye-bye folks"}, 
    {32, 17, "nissehat "}, 
    {25, 5, "null"}, 
};

//------------------------------------------------------------------------------
// Byte Code
//------------------------------------------------------------------------------

const u1 code[] = {

    //------------------------------------------------------------------------------
    // (24) java/lang/String#<init>#([CII)V
    //------------------------------------------------------------------------------

    // java/lang/String#<init>#([CII)V:9
    /* 0000 */      c_aload_0()
    /* 0001 */      c_invokespecial(0x00, 0x00)

    // java/lang/String#<init>#([CII)V:10
    /* 0004 */      c_aload_0()
    /* 0005 */      c_iload_3()
    /* 0006 */      c_newarray(0x05)
    /* 0008 */      c_putfield(0x00, 0x00)

    // java/lang/String#<init>#([CII)V:11
    /* 000b */      c_iconst_0()
    /* 000c */      c_istore(0x04)
    /* 000e */      c_iload(0x04)
    /* 0010 */      c_iload_3()
    /* 0011 */      c_if_icmpge(0x00, 0x16)

    // java/lang/String#<init>#([CII)V:12
    /* 0014 */      c_aload_0()
    /* 0015 */      c_getfield(0x00, 0x00)
    /* 0018 */      c_iload(0x04)
    /* 001a */      c_aload_1()
    /* 001b */      c_iload(0x04)
    /* 001d */      c_iload_2()
    /* 001e */      c_iadd()
    /* 001f */      c_caload()
    /* 0020 */      c_castore()

    // java/lang/String#<init>#([CII)V:11
    /* 0021 */      c_iinc(0x04, 0x01)
    /* 0024 */      c_goto(0xff, 0xea)

    // java/lang/String#<init>#([CII)V:14
    /* 0027 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (24) java/lang/String#<init>#([C)V
    //------------------------------------------------------------------------------

    // java/lang/String#<init>#([C)V:16
    /* 0028 */      c_aload_0()
    /* 0029 */      c_invokespecial(0x00, 0x00)

    // java/lang/String#<init>#([C)V:18
    /* 002c */      c_aload_0()
    /* 002d */      c_aload_1()
    /* 002e */      c_arraylength()
    /* 002f */      c_newarray(0x05)
    /* 0031 */      c_putfield(0x00, 0x00)

    // java/lang/String#<init>#([C)V:19
    /* 0034 */      c_iconst_0()
    /* 0035 */      c_istore_2()
    /* 0036 */      c_iload_2()
    /* 0037 */      c_aload_1()
    /* 0038 */      c_arraylength()
    /* 0039 */      c_if_icmpge(0x00, 0x12)

    // java/lang/String#<init>#([C)V:20
    /* 003c */      c_aload_0()
    /* 003d */      c_getfield(0x00, 0x00)
    /* 0040 */      c_iload_2()
    /* 0041 */      c_aload_1()
    /* 0042 */      c_iload_2()
    /* 0043 */      c_caload()
    /* 0044 */      c_castore()

    // java/lang/String#<init>#([C)V:19
    /* 0045 */      c_iinc(0x02, 0x01)
    /* 0048 */      c_goto(0xff, 0xee)

    // java/lang/String#<init>#([C)V:22
    /* 004b */      c_vreturn()

    //------------------------------------------------------------------------------
    // (24) java/lang/String#length#()I
    //------------------------------------------------------------------------------

    // java/lang/String#length#()I:25
    /* 004c */      c_aload_0()
    /* 004d */      c_getfield(0x00, 0x00)
    /* 0050 */      c_arraylength()
    /* 0051 */      c_ireturn()

    //------------------------------------------------------------------------------
    // (24) java/lang/String#getChars#(II[CI)V
    //------------------------------------------------------------------------------

    // java/lang/String#getChars#(II[CI)V:44
    /* 0052 */      c_iload_1()
    /* 0053 */      c_istore(0x05)
    /* 0055 */      c_iload(0x05)
    /* 0057 */      c_iload_2()
    /* 0058 */      c_if_icmpge(0x00, 0x19)

    // java/lang/String#getChars#(II[CI)V:45
    /* 005b */      c_aload_3()
    /* 005c */      c_iload(0x04)
    /* 005e */      c_iload(0x05)
    /* 0060 */      c_iadd()
    /* 0061 */      c_iload_1()
    /* 0062 */      c_isub()
    /* 0063 */      c_aload_0()
    /* 0064 */      c_getfield(0x00, 0x00)
    /* 0067 */      c_iload(0x05)
    /* 0069 */      c_caload()
    /* 006a */      c_castore()

    // java/lang/String#getChars#(II[CI)V:44
    /* 006b */      c_iinc(0x05, 0x01)
    /* 006e */      c_goto(0xff, 0xe7)

    // java/lang/String#getChars#(II[CI)V:47
    /* 0071 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (24) java/lang/String#toString#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/String#toString#()Ljava/lang/String;:51
    /* 0072 */      c_aload_0()
    /* 0073 */      c_areturn()

    //------------------------------------------------------------------------------
    // (24) java/lang/String#hashCode#()I
    //------------------------------------------------------------------------------

    // java/lang/String#hashCode#()I:57
    /* 0074 */      c_iconst_1()
    /* 0075 */      c_istore_2()

    // java/lang/String#hashCode#()I:58
    /* 0076 */      c_bipush(0x1f)
    /* 0078 */      c_iload_2()
    /* 0079 */      c_imul()
    /* 007a */      c_aload_0()
    /* 007b */      c_getfield(0x00, 0x00)
    /* 007e */      c_invokestatic(0x00, 0x01)
    /* 0081 */      c_iadd()
    /* 0082 */      c_istore_2()

    // java/lang/String#hashCode#()I:59
    /* 0083 */      c_iload_2()
    /* 0084 */      c_ireturn()

    //------------------------------------------------------------------------------
    // (0) java/lang/Object#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/Object#<init>#()V:7
    /* 0085 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (0) java/lang/Object#toString#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/Object#toString#()Ljava/lang/String;:25
    /* 0086 */      c_new(0x00, 0x02)
    /* 0089 */      c_dup()
    /* 008a */      c_invokespecial(0x00, 0x00)
    /* 008d */      c_aload_0()
    /* 008e */      c_invokevirtual(0x00, 0x01)
    /* 0091 */      c_invokevirtual(0x00, 0x02)
    /* 0094 */      c_invokevirtual(0x00, 0x03)
    /* 0097 */      c_ldc(0x07)
    /* 0099 */      c_invokevirtual(0x00, 0x03)
    /* 009c */      c_aload_0()
    /* 009d */      c_invokevirtual(0x00, 0x04)
    /* 00a0 */      c_invokevirtual(0x00, 0x05)
    /* 00a3 */      c_invokevirtual(0x00, 0x06)
    /* 00a6 */      c_areturn()

    //------------------------------------------------------------------------------
    // (10) java/lang/Class#getName#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/Class#getName#()Ljava/lang/String;:21
    /* 00a7 */      c_new(0x00, 0x02)
    /* 00aa */      c_dup()
    /* 00ab */      c_invokespecial(0x00, 0x00)
    /* 00ae */      c_ldc(0x04)
    /* 00b0 */      c_invokevirtual(0x00, 0x01)
    /* 00b3 */      c_aload_0()
    /* 00b4 */      c_getfield(0x00, 0x00)
    /* 00b7 */      c_invokevirtual(0x00, 0x02)
    /* 00ba */      c_invokevirtual(0x00, 0x03)
    /* 00bd */      c_areturn()

    //------------------------------------------------------------------------------
    // (10) java/lang/Class#toString#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/Class#toString#()Ljava/lang/String;:26
    /* 00be */      c_aload_0()
    /* 00bf */      c_invokevirtual(0x00, 0x04)
    /* 00c2 */      c_areturn()

    //------------------------------------------------------------------------------
    // (9) java/lang/ArrayIndexOutOfBoundsException#<init>#(I)V
    //------------------------------------------------------------------------------

    // java/lang/ArrayIndexOutOfBoundsException#<init>#(I)V:9
    /* 00c3 */      c_aload_0()
    /* 00c4 */      c_new(0x00, 0x02)
    /* 00c7 */      c_dup()
    /* 00c8 */      c_invokespecial(0x00, 0x01)
    /* 00cb */      c_ldc(0x04)
    /* 00cd */      c_invokevirtual(0x00, 0x02)
    /* 00d0 */      c_iload_1()
    /* 00d1 */      c_invokevirtual(0x00, 0x03)
    /* 00d4 */      c_invokevirtual(0x00, 0x04)
    /* 00d7 */      c_invokespecial(0x00, 0x00)

    // java/lang/ArrayIndexOutOfBoundsException#<init>#(I)V:10
    /* 00da */      c_vreturn()

    //------------------------------------------------------------------------------
    // (8) java/lang/ArithmeticException#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/ArithmeticException#<init>#(Ljava/lang/String;)V:6
    /* 00db */      c_aload_0()
    /* 00dc */      c_aload_1()
    /* 00dd */      c_invokespecial(0x00, 0x00)

    // java/lang/ArithmeticException#<init>#(Ljava/lang/String;)V:7
    /* 00e0 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (11) java/lang/ClassCastException#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/ClassCastException#<init>#()V:3
    /* 00e1 */      c_aload_0()
    /* 00e2 */      c_invokespecial(0x00, 0x00)
    /* 00e5 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (14) java/lang/IllegalMonitorStateException#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/IllegalMonitorStateException#<init>#(Ljava/lang/String;)V:8
    /* 00e6 */      c_aload_0()
    /* 00e7 */      c_aload_1()
    /* 00e8 */      c_invokespecial(0x00, 0x00)

    // java/lang/IllegalMonitorStateException#<init>#(Ljava/lang/String;)V:9
    /* 00eb */      c_vreturn()

    //------------------------------------------------------------------------------
    // (16) java/lang/InterruptedException#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/InterruptedException#<init>#()V:3
    /* 00ec */      c_aload_0()
    /* 00ed */      c_invokespecial(0x00, 0x00)
    /* 00f0 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (17) java/lang/NegativeArraySizeException#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/NegativeArraySizeException#<init>#()V:3
    /* 00f1 */      c_aload_0()
    /* 00f2 */      c_invokespecial(0x00, 0x00)
    /* 00f5 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (18) java/lang/NullPointerException#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/NullPointerException#<init>#(Ljava/lang/String;)V:5
    /* 00f6 */      c_aload_0()
    /* 00f7 */      c_aload_1()
    /* 00f8 */      c_invokespecial(0x00, 0x00)

    // java/lang/NullPointerException#<init>#(Ljava/lang/String;)V:6
    /* 00fb */      c_vreturn()

    //------------------------------------------------------------------------------
    // (18) java/lang/NullPointerException#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/NullPointerException#<init>#()V:9
    /* 00fc */      c_aload_0()
    /* 00fd */      c_aconst_null()
    /* 00fe */      c_invokespecial(0x00, 0x01)

    // java/lang/NullPointerException#<init>#()V:10
    /* 0101 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (21) java/lang/OutOfMemoryError#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/OutOfMemoryError#<init>#()V:10
    /* 0102 */      c_aload_0()
    /* 0103 */      c_invokespecial(0x00, 0x00)

    // java/lang/OutOfMemoryError#<init>#()V:11
    /* 0106 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (21) java/lang/OutOfMemoryError#getInstance#()Ljava/lang/OutOfMemoryError;
    //------------------------------------------------------------------------------

    // java/lang/OutOfMemoryError#getInstance#()Ljava/lang/OutOfMemoryError;:18
    /* 0107 */      c_getstatic(0x00, 0x00)
    /* 010a */      c_areturn()

    //------------------------------------------------------------------------------
    // (21) java/lang/OutOfMemoryError#<clinit>#()V
    //------------------------------------------------------------------------------

    // java/lang/OutOfMemoryError#<clinit>#()V:5
    /* 010b */      c_new(0x00, 0x04)
    /* 010e */      c_dup()
    /* 010f */      c_invokespecial(0x00, 0x01)
    /* 0112 */      c_putstatic(0x00, 0x00)
    /* 0115 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (29) java/lang/VirtualMachineError#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/VirtualMachineError#<init>#()V:8
    /* 0116 */      c_aload_0()
    /* 0117 */      c_invokespecial(0x00, 0x00)

    // java/lang/VirtualMachineError#<init>#()V:9
    /* 011a */      c_vreturn()

    //------------------------------------------------------------------------------
    // (12) java/lang/Error#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/Error#<init>#()V:8
    /* 011b */      c_aload_0()
    /* 011c */      c_invokespecial(0x00, 0x00)

    // java/lang/Error#<init>#()V:9
    /* 011f */      c_vreturn()

    //------------------------------------------------------------------------------
    // (28) java/lang/Throwable#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/Throwable#<init>#()V:11
    /* 0120 */      c_aload_0()
    /* 0121 */      c_aconst_null()
    /* 0122 */      c_invokespecial(0x00, 0x00)

    // java/lang/Throwable#<init>#()V:12
    /* 0125 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (28) java/lang/Throwable#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:14
    /* 0126 */      c_aload_0()
    /* 0127 */      c_invokespecial(0x00, 0x01)

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:15
    /* 012a */      c_aload_0()
    /* 012b */      c_aload_1()
    /* 012c */      c_putfield(0x00, 0x00)

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:16
    /* 012f */      c_aload_0()
    /* 0130 */      c_invokespecial(0x00, 0x02)
    /* 0133 */      c_istore_2()

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:17
    /* 0134 */      c_aload_0()
    /* 0135 */      c_iload_2()
    /* 0136 */      c_newarray(0x0a)
    /* 0138 */      c_putfield(0x00, 0x01)

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:18
    /* 013b */      c_iconst_0()
    /* 013c */      c_istore_3()
    /* 013d */      c_iload_3()
    /* 013e */      c_iload_2()
    /* 013f */      c_if_icmpge(0x00, 0x14)

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:19
    /* 0142 */      c_aload_0()
    /* 0143 */      c_getfield(0x00, 0x01)
    /* 0146 */      c_iload_3()
    /* 0147 */      c_aload_0()
    /* 0148 */      c_iload_3()
    /* 0149 */      c_invokespecial(0x00, 0x03)
    /* 014c */      c_iastore()

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:18
    /* 014d */      c_iinc(0x03, 0x01)
    /* 0150 */      c_goto(0xff, 0xed)

    // java/lang/Throwable#<init>#(Ljava/lang/String;)V:21
    /* 0153 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (28) java/lang/Throwable#printStackTrace#()V
    //------------------------------------------------------------------------------

    // java/lang/Throwable#printStackTrace#()V:39
    /* 0154 */      c_getstatic(0x00, 0x02)
    /* 0157 */      c_aload_0()
    /* 0158 */      c_invokevirtual(0x00, 0x04)
    /* 015b */      c_invokevirtual(0x00, 0x05)

    // java/lang/Throwable#printStackTrace#()V:40
    /* 015e */      c_getstatic(0x00, 0x02)
    /* 0161 */      c_aload_0()
    /* 0162 */      c_getfield(0x00, 0x00)
    /* 0165 */      c_ifnull(0x00, 0x1c)
    /* 0168 */      c_new(0x00, 0x0a)
    /* 016b */      c_dup()
    /* 016c */      c_invokespecial(0x00, 0x06)
    /* 016f */      c_ldc(0x0c)
    /* 0171 */      c_invokevirtual(0x00, 0x07)
    /* 0174 */      c_aload_0()
    /* 0175 */      c_getfield(0x00, 0x00)
    /* 0178 */      c_invokevirtual(0x00, 0x07)
    /* 017b */      c_invokevirtual(0x00, 0x08)
    /* 017e */      c_goto(0x00, 0x05)
    /* 0181 */      c_ldc(0x0f)
    /* 0183 */      c_invokevirtual(0x00, 0x09)

    // java/lang/Throwable#printStackTrace#()V:42
    /* 0186 */      c_iconst_0()
    /* 0187 */      c_istore_1()

    // java/lang/Throwable#printStackTrace#()V:43
    /* 0188 */      c_aload_0()
    /* 0189 */      c_getfield(0x00, 0x01)
    /* 018c */      c_astore_2()
    /* 018d */      c_aload_2()
    /* 018e */      c_arraylength()
    /* 018f */      c_istore_3()
    /* 0190 */      c_iconst_0()
    /* 0191 */      c_istore(0x04)
    /* 0193 */      c_iload(0x04)
    /* 0195 */      c_iload_3()
    /* 0196 */      c_if_icmpge(0x00, 0x30)
    /* 0199 */      c_aload_2()
    /* 019a */      c_iload(0x04)
    /* 019c */      c_iaload()
    /* 019d */      c_istore(0x05)

    // java/lang/Throwable#printStackTrace#()V:44
    /* 019f */      c_iload_1()
    /* 01a0 */      c_ifeq(0x00, 0x0e)

    // java/lang/Throwable#printStackTrace#()V:45
    /* 01a3 */      c_getstatic(0x00, 0x02)
    /* 01a6 */      c_ldc(0x11)
    /* 01a8 */      c_invokevirtual(0x00, 0x0a)
    /* 01ab */      c_goto(0x00, 0x0d)

    // java/lang/Throwable#printStackTrace#()V:47
    /* 01ae */      c_getstatic(0x00, 0x02)
    /* 01b1 */      c_ldc(0x13)
    /* 01b3 */      c_invokevirtual(0x00, 0x0a)

    // java/lang/Throwable#printStackTrace#()V:48
    /* 01b6 */      c_iconst_1()
    /* 01b7 */      c_istore_1()

    // java/lang/Throwable#printStackTrace#()V:50
    /* 01b8 */      c_getstatic(0x00, 0x02)
    /* 01bb */      c_iload(0x05)
    /* 01bd */      c_invokevirtual(0x00, 0x0b)

    // java/lang/Throwable#printStackTrace#()V:43
    /* 01c0 */      c_iinc(0x04, 0x01)
    /* 01c3 */      c_goto(0xff, 0xd0)

    // java/lang/Throwable#printStackTrace#()V:52
    /* 01c6 */      c_getstatic(0x00, 0x02)
    /* 01c9 */      c_ldc(0x0f)
    /* 01cb */      c_invokevirtual(0x00, 0x09)

    // java/lang/Throwable#printStackTrace#()V:53
    /* 01ce */      c_vreturn()

    //------------------------------------------------------------------------------
    // (28) java/lang/Throwable#toString#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/Throwable#toString#()Ljava/lang/String;:57
    /* 01cf */      c_new(0x00, 0x0a)
    /* 01d2 */      c_dup()
    /* 01d3 */      c_invokespecial(0x00, 0x06)
    /* 01d6 */      c_ldc(0x15)
    /* 01d8 */      c_invokevirtual(0x00, 0x07)
    /* 01db */      c_aload_0()
    /* 01dc */      c_getfield(0x00, 0x00)
    /* 01df */      c_invokevirtual(0x00, 0x07)
    /* 01e2 */      c_invokevirtual(0x00, 0x08)
    /* 01e5 */      c_areturn()

    //------------------------------------------------------------------------------
    // (27) java/lang/Thread#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/Thread#<init>#()V:68
    /* 01e6 */      c_aload_0()
    /* 01e7 */      c_aconst_null()
    /* 01e8 */      c_invokespecial(0x00, 0x00)

    // java/lang/Thread#<init>#()V:69
    /* 01eb */      c_vreturn()

    //------------------------------------------------------------------------------
    // (27) java/lang/Thread#<init>#(Ljava/lang/Runnable;)V
    //------------------------------------------------------------------------------

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:76
    /* 01ec */      c_aload_0()
    /* 01ed */      c_invokespecial(0x00, 0x01)

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:77
    /* 01f0 */      c_aload_0()
    /* 01f1 */      c_aload_1()
    /* 01f2 */      c_putfield(0x00, 0x00)

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:79
    /* 01f5 */      c_aload_0()
    /* 01f6 */      c_getstatic(0x00, 0x01)
    /* 01f9 */      c_dup2()
    /* 01fa */      c_lconst_1()
    /* 01fb */      c_ladd()
    /* 01fc */      c_putstatic(0x00, 0x01)
    /* 01ff */      c_putfield(0x00, 0x02)

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:80
    /* 0202 */      c_aload_0()
    /* 0203 */      c_iconst_0()
    /* 0204 */      c_putfield(0x00, 0x03)

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:81
    /* 0207 */      c_aload_0()
    /* 0208 */      c_iconst_0()
    /* 0209 */      c_putfield(0x00, 0x04)

    // java/lang/Thread#<init>#(Ljava/lang/Runnable;)V:82
    /* 020c */      c_vreturn()

    //------------------------------------------------------------------------------
    // (27) java/lang/Thread#runFromNative#()V
    //------------------------------------------------------------------------------

    // java/lang/Thread#runFromNative#()V:103
    /* 020d */      c_aload_0()
    /* 020e */      c_getfield(0x00, 0x00)
    /* 0211 */      c_ifnull(0x00, 0x0f)

    // java/lang/Thread#runFromNative#()V:104
    /* 0214 */      c_aload_0()
    /* 0215 */      c_getfield(0x00, 0x00)
    /* 0218 */      c_invokeinterface(0x00, 0x03, 0x01, 0x00)
    /* 021d */      c_goto(0x00, 0x07)

    // java/lang/Thread#runFromNative#()V:106
    /* 0220 */      c_aload_0()
    /* 0221 */      c_invokevirtual(0x00, 0x04)

    // java/lang/Thread#runFromNative#()V:110
    /* 0224 */      c_goto(0x00, 0x08)

    // java/lang/Thread#runFromNative#()V:108
    /* 0227 */      c_astore_1()

    // java/lang/Thread#runFromNative#()V:109
    /* 0228 */      c_aload_1()
    /* 0229 */      c_invokevirtual(0x00, 0x05)

    // java/lang/Thread#runFromNative#()V:112
    /* 022c */      c_aload_0()
    /* 022d */      c_iconst_5()
    /* 022e */      c_putfield(0x00, 0x03)

    // java/lang/Thread#runFromNative#()V:119
    /* 0231 */      c_invokestatic(0x00, 0x06)

    // java/lang/Thread#runFromNative#()V:120
    /* 0234 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (27) java/lang/Thread#run#()V
    //------------------------------------------------------------------------------

    // java/lang/Thread#run#()V:131
    /* 0235 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (27) java/lang/Thread#<clinit>#()V
    //------------------------------------------------------------------------------

    // java/lang/Thread#<clinit>#()V:27
    /* 0236 */      c_lconst_0()
    /* 0237 */      c_putstatic(0x00, 0x01)

    // java/lang/Thread#<clinit>#()V:58
    /* 023a */      c_new(0x00, 0x17)
    /* 023d */      c_dup()
    /* 023e */      c_invokespecial(0x00, 0x07)
    /* 0241 */      c_putstatic(0x00, 0x05)

    // java/lang/Thread#<clinit>#()V:61
    /* 0244 */      c_getstatic(0x00, 0x05)
    /* 0247 */      c_invokespecial(0x00, 0x02)

    // java/lang/Thread#<clinit>#()V:62
    /* 024a */      c_vreturn()

    //------------------------------------------------------------------------------
    // (31) thinj/regression/AllTests#main#([Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // thinj/regression/AllTests#main#([Ljava/lang/String;)V:5
    /* 024b */      c_getstatic(0x00, 0x00)
    /* 024e */      c_ldc(0x03)
    /* 0250 */      c_invokevirtual(0x00, 0x00)

    // thinj/regression/AllTests#main#([Ljava/lang/String;)V:107
    /* 0253 */      c_getstatic(0x00, 0x00)
    /* 0256 */      c_ldc(0x05)
    /* 0258 */      c_invokevirtual(0x00, 0x00)

    // thinj/regression/AllTests#main#([Ljava/lang/String;)V:108
    /* 025b */      c_aconst_null()
    /* 025c */      c_invokestatic(0x00, 0x01)

    // thinj/regression/AllTests#main#([Ljava/lang/String;)V:114
    /* 025f */      c_vreturn()

    //------------------------------------------------------------------------------
    // (26) java/lang/System#<clinit>#()V
    //------------------------------------------------------------------------------

    // java/lang/System#<clinit>#()V:6
    /* 0260 */      c_new(0x00, 0x02)
    /* 0263 */      c_dup()
    /* 0264 */      c_invokespecial(0x00, 0x00)
    /* 0267 */      c_putstatic(0x00, 0x00)

    // java/lang/System#<clinit>#()V:7
    /* 026a */      c_new(0x00, 0x02)
    /* 026d */      c_dup()
    /* 026e */      c_invokespecial(0x00, 0x00)
    /* 0271 */      c_putstatic(0x00, 0x01)
    /* 0274 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (7) java/io/PrintStream#<init>#()V
    //------------------------------------------------------------------------------

    // java/io/PrintStream#<init>#()V:3
    /* 0275 */      c_aload_0()
    /* 0276 */      c_invokespecial(0x00, 0x00)
    /* 0279 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (7) java/io/PrintStream#println#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/io/PrintStream#println#(Ljava/lang/String;)V:9
    /* 027a */      c_aload_1()
    /* 027b */      c_invokestatic(0x00, 0x01)

    // java/io/PrintStream#println#(Ljava/lang/String;)V:10
    /* 027e */      c_vreturn()

    //------------------------------------------------------------------------------
    // (7) java/io/PrintStream#print#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/io/PrintStream#print#(Ljava/lang/String;)V:13
    /* 027f */      c_aload_1()
    /* 0280 */      c_invokestatic(0x00, 0x02)

    // java/io/PrintStream#print#(Ljava/lang/String;)V:14
    /* 0283 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (7) java/io/PrintStream#print#(I)V
    //------------------------------------------------------------------------------

    // java/io/PrintStream#print#(I)V:29
    /* 0284 */      c_aload_0()
    /* 0285 */      c_new(0x00, 0x09)
    /* 0288 */      c_dup()
    /* 0289 */      c_invokespecial(0x00, 0x04)
    /* 028c */      c_ldc(0x04)
    /* 028e */      c_invokevirtual(0x00, 0x05)
    /* 0291 */      c_iload_1()
    /* 0292 */      c_invokevirtual(0x00, 0x06)
    /* 0295 */      c_invokevirtual(0x00, 0x07)
    /* 0298 */      c_invokevirtual(0x00, 0x03)

    // java/io/PrintStream#print#(I)V:30
    /* 029b */      c_vreturn()

    //------------------------------------------------------------------------------
    // (7) java/io/PrintStream#print#(Ljava/lang/Object;)V
    //------------------------------------------------------------------------------

    // java/io/PrintStream#print#(Ljava/lang/Object;)V:49
    /* 029c */      c_aload_1()
    /* 029d */      c_ifnonnull(0x00, 0x08)
    /* 02a0 */      c_ldc(0x11)
    /* 02a2 */      c_goto(0x00, 0x07)
    /* 02a5 */      c_aload_1()
    /* 02a6 */      c_invokevirtual(0x00, 0x08)
    /* 02a9 */      c_invokestatic(0x00, 0x02)

    // java/io/PrintStream#print#(Ljava/lang/Object;)V:50
    /* 02ac */      c_vreturn()

    //------------------------------------------------------------------------------
    // (32) thinj/regression/ThreadTest#main#([Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // thinj/regression/ThreadTest#main#([Ljava/lang/String;)V:9
    /* 02ad */      c_getstatic(0x00, 0x04)
    /* 02b0 */      c_ldc(0x09)
    /* 02b2 */      c_invokevirtual(0x00, 0x01)

    // thinj/regression/ThreadTest#main#([Ljava/lang/String;)V:10
    /* 02b5 */      c_invokestatic(0x00, 0x02)

    // thinj/regression/ThreadTest#main#([Ljava/lang/String;)V:11
    /* 02b8 */      c_invokestatic(0x00, 0x03)

    // thinj/regression/ThreadTest#main#([Ljava/lang/String;)V:27
    /* 02bb */      c_getstatic(0x00, 0x04)
    /* 02be */      c_ldc(0x0d)
    /* 02c0 */      c_invokevirtual(0x00, 0x01)

    // thinj/regression/ThreadTest#main#([Ljava/lang/String;)V:28
    /* 02c3 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (32) thinj/regression/ThreadTest#simpleYield#()V
    //------------------------------------------------------------------------------

    // thinj/regression/ThreadTest#simpleYield#()V:31
    /* 02c4 */      c_iconst_0()
    /* 02c5 */      c_putstatic(0x00, 0x03)

    // thinj/regression/ThreadTest#simpleYield#()V:32
    /* 02c8 */      c_iconst_0()
    /* 02c9 */      c_istore_0()
    /* 02ca */      c_iload_0()
    /* 02cb */      c_bipush(0x0a)
    /* 02cd */      c_if_icmpge(0x00, 0x0c)

    // thinj/regression/ThreadTest#simpleYield#()V:33
    /* 02d0 */      c_invokestatic(0x00, 0x04)

    // thinj/regression/ThreadTest#simpleYield#()V:32
    /* 02d3 */      c_iinc(0x00, 0x01)
    /* 02d6 */      c_goto(0xff, 0xf4)

    // thinj/regression/ThreadTest#simpleYield#()V:35
    /* 02d9 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (32) thinj/regression/ThreadTest#yieldAndGC#()V
    //------------------------------------------------------------------------------

    // thinj/regression/ThreadTest#yieldAndGC#()V:38
    /* 02da */      c_iconst_0()
    /* 02db */      c_istore_0()
    /* 02dc */      c_iload_0()
    /* 02dd */      c_sipush(0x03, 0xe8)
    /* 02e0 */      c_if_icmpge(0x00, 0x2e)

    // thinj/regression/ThreadTest#yieldAndGC#()V:39
    /* 02e3 */      c_invokestatic(0x00, 0x04)

    // thinj/regression/ThreadTest#yieldAndGC#()V:40
    /* 02e6 */      c_new(0x00, 0x0f)
    /* 02e9 */      c_dup()
    /* 02ea */      c_invokespecial(0x00, 0x05)
    /* 02ed */      c_ldc(0x11)
    /* 02ef */      c_invokevirtual(0x00, 0x06)
    /* 02f2 */      c_iload_0()
    /* 02f3 */      c_invokevirtual(0x00, 0x07)
    /* 02f6 */      c_invokevirtual(0x00, 0x08)
    /* 02f9 */      c_astore_1()

    // thinj/regression/ThreadTest#yieldAndGC#()V:41
    /* 02fa */      c_iload_0()
    /* 02fb */      c_bipush(0x32)
    /* 02fd */      c_irem()
    /* 02fe */      c_ifne(0x00, 0x0a)

    // thinj/regression/ThreadTest#yieldAndGC#()V:42
    /* 0301 */      c_getstatic(0x00, 0x04)
    /* 0304 */      c_aload_1()
    /* 0305 */      c_invokevirtual(0x00, 0x01)

    // thinj/regression/ThreadTest#yieldAndGC#()V:38
    /* 0308 */      c_iinc(0x00, 0x01)
    /* 030b */      c_goto(0xff, 0xd1)

    // thinj/regression/ThreadTest#yieldAndGC#()V:45
    /* 030e */      c_vreturn()

    //------------------------------------------------------------------------------
    // (32) thinj/regression/ThreadTest#<clinit>#()V
    //------------------------------------------------------------------------------

    // thinj/regression/ThreadTest#<clinit>#()V:4
    /* 030f */      c_iconst_0()
    /* 0310 */      c_putstatic(0x00, 0x03)

    // thinj/regression/ThreadTest#<clinit>#()V:5
    /* 0313 */      c_iconst_0()
    /* 0314 */      c_putstatic(0x00, 0x00)

    // thinj/regression/ThreadTest#<clinit>#()V:6
    /* 0317 */      c_iconst_0()
    /* 0318 */      c_putstatic(0x00, 0x02)

    // thinj/regression/ThreadTest#<clinit>#()V:276
    /* 031b */      c_new(0x00, 0x1e)
    /* 031e */      c_dup()
    /* 031f */      c_invokespecial(0x00, 0x00)
    /* 0322 */      c_putstatic(0x00, 0x01)
    /* 0325 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (25) java/lang/StringBuilder#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/StringBuilder#<init>#()V:11
    /* 0326 */      c_aload_0()
    /* 0327 */      c_invokespecial(0x00, 0x00)

    // java/lang/StringBuilder#<init>#()V:12
    /* 032a */      c_aload_0()
    /* 032b */      c_iconst_0()
    /* 032c */      c_newarray(0x05)
    /* 032e */      c_putfield(0x00, 0x00)

    // java/lang/StringBuilder#<init>#()V:13
    /* 0331 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (25) java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;
    //------------------------------------------------------------------------------

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:16
    /* 0332 */      c_aload_1()
    /* 0333 */      c_ifnonnull(0x00, 0x0a)

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:17
    /* 0336 */      c_aload_0()
    /* 0337 */      c_ldc(0x05)
    /* 0339 */      c_invokevirtual(0x00, 0x03)
    /* 033c */      c_areturn()

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:19
    /* 033d */      c_aload_0()
    /* 033e */      c_getfield(0x00, 0x00)
    /* 0341 */      c_arraylength()
    /* 0342 */      c_aload_1()
    /* 0343 */      c_invokevirtual(0x00, 0x01)
    /* 0346 */      c_iadd()
    /* 0347 */      c_newarray(0x05)
    /* 0349 */      c_astore_2()

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:21
    /* 034a */      c_iconst_0()
    /* 034b */      c_istore_3()
    /* 034c */      c_iload_3()
    /* 034d */      c_aload_0()
    /* 034e */      c_getfield(0x00, 0x00)
    /* 0351 */      c_arraylength()
    /* 0352 */      c_if_icmpge(0x00, 0x12)

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:22
    /* 0355 */      c_aload_2()
    /* 0356 */      c_iload_3()
    /* 0357 */      c_aload_0()
    /* 0358 */      c_getfield(0x00, 0x00)
    /* 035b */      c_iload_3()
    /* 035c */      c_caload()
    /* 035d */      c_castore()

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:21
    /* 035e */      c_iinc(0x03, 0x01)
    /* 0361 */      c_goto(0xff, 0xeb)

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:25
    /* 0364 */      c_aload_1()
    /* 0365 */      c_iconst_0()
    /* 0366 */      c_aload_1()
    /* 0367 */      c_invokevirtual(0x00, 0x01)
    /* 036a */      c_aload_2()
    /* 036b */      c_aload_0()
    /* 036c */      c_getfield(0x00, 0x00)
    /* 036f */      c_arraylength()
    /* 0370 */      c_invokevirtual(0x00, 0x02)

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:26
    /* 0373 */      c_aload_0()
    /* 0374 */      c_aload_2()
    /* 0375 */      c_putfield(0x00, 0x00)

    // java/lang/StringBuilder#append#(Ljava/lang/String;)Ljava/lang/StringBuilder;:28
    /* 0378 */      c_aload_0()
    /* 0379 */      c_areturn()

    //------------------------------------------------------------------------------
    // (25) java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;
    //------------------------------------------------------------------------------

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:42
    /* 037a */      c_iload_1()
    /* 037b */      c_ifge(0x00, 0x07)
    /* 037e */      c_iconst_1()
    /* 037f */      c_goto(0x00, 0x04)
    /* 0382 */      c_iconst_0()
    /* 0383 */      c_istore_2()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:43
    /* 0384 */      c_iload_2()
    /* 0385 */      c_ifeq(0x00, 0x06)

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:44
    /* 0388 */      c_iload_1()
    /* 0389 */      c_ineg()
    /* 038a */      c_istore_1()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:46
    /* 038b */      c_bipush(0x0b)
    /* 038d */      c_newarray(0x05)
    /* 038f */      c_astore_3()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:47
    /* 0390 */      c_aload_3()
    /* 0391 */      c_arraylength()
    /* 0392 */      c_istore(0x04)

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:49
    /* 0394 */      c_aload_3()
    /* 0395 */      c_iinc(0x04, 0xff)
    /* 0398 */      c_iload(0x04)
    /* 039a */      c_bipush(0x30)
    /* 039c */      c_iload_1()
    /* 039d */      c_bipush(0x0a)
    /* 039f */      c_irem()
    /* 03a0 */      c_iadd()
    /* 03a1 */      c_i2c()
    /* 03a2 */      c_castore()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:50
    /* 03a3 */      c_iload_1()
    /* 03a4 */      c_bipush(0x0a)
    /* 03a6 */      c_idiv()
    /* 03a7 */      c_istore_1()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:51
    /* 03a8 */      c_iload_1()
    /* 03a9 */      c_ifgt(0xff, 0xeb)

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:53
    /* 03ac */      c_iload_2()
    /* 03ad */      c_ifeq(0x00, 0x0c)

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:54
    /* 03b0 */      c_aload_3()
    /* 03b1 */      c_iinc(0x04, 0xff)
    /* 03b4 */      c_iload(0x04)
    /* 03b6 */      c_bipush(0x2d)
    /* 03b8 */      c_castore()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:57
    /* 03b9 */      c_aload_0()
    /* 03ba */      c_new(0x00, 0x0a)
    /* 03bd */      c_dup()
    /* 03be */      c_aload_3()
    /* 03bf */      c_iload(0x04)
    /* 03c1 */      c_aload_3()
    /* 03c2 */      c_arraylength()
    /* 03c3 */      c_iload(0x04)
    /* 03c5 */      c_isub()
    /* 03c6 */      c_invokespecial(0x00, 0x04)
    /* 03c9 */      c_invokevirtual(0x00, 0x03)
    /* 03cc */      c_pop()

    // java/lang/StringBuilder#append#(I)Ljava/lang/StringBuilder;:58
    /* 03cd */      c_aload_0()
    /* 03ce */      c_areturn()

    //------------------------------------------------------------------------------
    // (25) java/lang/StringBuilder#toString#()Ljava/lang/String;
    //------------------------------------------------------------------------------

    // java/lang/StringBuilder#toString#()Ljava/lang/String;:78
    /* 03cf */      c_new(0x00, 0x0a)
    /* 03d2 */      c_dup()
    /* 03d3 */      c_aload_0()
    /* 03d4 */      c_getfield(0x00, 0x00)
    /* 03d7 */      c_invokespecial(0x00, 0x05)
    /* 03da */      c_areturn()

    //------------------------------------------------------------------------------
    // (23) java/lang/RuntimeException#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/RuntimeException#<init>#(Ljava/lang/String;)V:5
    /* 03db */      c_aload_0()
    /* 03dc */      c_aload_1()
    /* 03dd */      c_invokespecial(0x00, 0x00)

    // java/lang/RuntimeException#<init>#(Ljava/lang/String;)V:6
    /* 03e0 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (23) java/lang/RuntimeException#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/RuntimeException#<init>#()V:7
    /* 03e1 */      c_aload_0()
    /* 03e2 */      c_invokespecial(0x00, 0x01)

    // java/lang/RuntimeException#<init>#()V:8
    /* 03e5 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (13) java/lang/Exception#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/Exception#<init>#(Ljava/lang/String;)V:5
    /* 03e6 */      c_aload_0()
    /* 03e7 */      c_aload_1()
    /* 03e8 */      c_invokespecial(0x00, 0x00)

    // java/lang/Exception#<init>#(Ljava/lang/String;)V:6
    /* 03eb */      c_vreturn()

    //------------------------------------------------------------------------------
    // (13) java/lang/Exception#<init>#()V
    //------------------------------------------------------------------------------

    // java/lang/Exception#<init>#()V:8
    /* 03ec */      c_aload_0()
    /* 03ed */      c_invokespecial(0x00, 0x01)

    // java/lang/Exception#<init>#()V:9
    /* 03f0 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (15) java/lang/IndexOutOfBoundsException#<init>#(Ljava/lang/String;)V
    //------------------------------------------------------------------------------

    // java/lang/IndexOutOfBoundsException#<init>#(Ljava/lang/String;)V:5
    /* 03f1 */      c_aload_0()
    /* 03f2 */      c_aload_1()
    /* 03f3 */      c_invokespecial(0x00, 0x00)

    // java/lang/IndexOutOfBoundsException#<init>#(Ljava/lang/String;)V:6
    /* 03f6 */      c_vreturn()

    //------------------------------------------------------------------------------
    // (30) java/util/Arrays#hashCode#([C)I
    //------------------------------------------------------------------------------

    // java/util/Arrays#hashCode#([C)I:6
    /* 03f7 */      c_bipush(0x25)
    /* 03f9 */      c_istore_1()

    // java/util/Arrays#hashCode#([C)I:7
    /* 03fa */      c_aload_0()
    /* 03fb */      c_astore_2()
    /* 03fc */      c_aload_2()
    /* 03fd */      c_arraylength()
    /* 03fe */      c_istore_3()
    /* 03ff */      c_iconst_0()
    /* 0400 */      c_istore(0x04)
    /* 0402 */      c_iload(0x04)
    /* 0404 */      c_iload_3()
    /* 0405 */      c_if_icmpge(0x00, 0x16)
    /* 0408 */      c_aload_2()
    /* 0409 */      c_iload(0x04)
    /* 040b */      c_caload()
    /* 040c */      c_istore(0x05)

    // java/util/Arrays#hashCode#([C)I:8
    /* 040e */      c_iload_1()
    /* 040f */      c_iconst_2()
    /* 0410 */      c_imul()
    /* 0411 */      c_iload(0x05)
    /* 0413 */      c_iadd()
    /* 0414 */      c_istore_1()

    // java/util/Arrays#hashCode#([C)I:7
    /* 0415 */      c_iinc(0x04, 0x01)
    /* 0418 */      c_goto(0xff, 0xea)

    // java/util/Arrays#hashCode#([C)I:10
    /* 041b */      c_iload_1()
    /* 041c */      c_ireturn()

    //------------------------------------------------------------------------------
    // (31) thinj/regression/AllTests#<jvminit>#()V
    //------------------------------------------------------------------------------
    /* 041d */      c_invokestatic(0x00, 0x02)
    /* 0420 */      c_invokestatic(0x00, 0x03)
    /* 0423 */      c_invokestatic(0x00, 0x04)
    /* 0426 */      c_invokestatic(0x00, 0x05)
    /* 0429 */      c_invokestatic(0x00, 0x06)
    /* 042c */      c_vreturn()
};
const u2 codeSize = 1069;

//------------------------------------------------------------------------------
// Constant Pools
//------------------------------------------------------------------------------

const constantPool const allConstantPools[] = {
    // 0: java/lang/Object
    {allMethodReferences0, 7, allMethods0, 4, NULL, 0, allFields0, 1},
    // 1: [B
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 2: [C
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 3: [I
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 4: [J
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 5: [Ljava/lang/Class
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 6: [Ljava/lang/Object
    {NULL, 0, NULL, 0, NULL, 0, NULL, 0},
    // 7: java/io/PrintStream
    {allMethodReferences7, 9, allMethods7, 7, NULL, 0, NULL, 0},
    // 8: java/lang/ArithmeticException
    {allMethodReferences8, 1, allMethods8, 1, NULL, 0, NULL, 0},
    // 9: java/lang/ArrayIndexOutOfBoundsException
    {allMethodReferences9, 5, allMethods9, 1, NULL, 0, NULL, 0},
    // 10: java/lang/Class
    {allMethodReferences10, 5, allMethods10, 2, allFieldReferences10, 1, allFields10, 3},
    // 11: java/lang/ClassCastException
    {allMethodReferences11, 1, allMethods11, 1, NULL, 0, NULL, 0},
    // 12: java/lang/Error
    {allMethodReferences12, 1, allMethods12, 1, NULL, 0, NULL, 0},
    // 13: java/lang/Exception
    {allMethodReferences13, 2, allMethods13, 2, NULL, 0, NULL, 0},
    // 14: java/lang/IllegalMonitorStateException
    {allMethodReferences14, 1, allMethods14, 1, NULL, 0, NULL, 0},
    // 15: java/lang/IndexOutOfBoundsException
    {allMethodReferences15, 1, allMethods15, 1, NULL, 0, NULL, 0},
    // 16: java/lang/InterruptedException
    {allMethodReferences16, 1, allMethods16, 1, NULL, 0, NULL, 0},
    // 17: java/lang/NegativeArraySizeException
    {allMethodReferences17, 1, allMethods17, 1, NULL, 0, NULL, 0},
    // 18: java/lang/NullPointerException
    {allMethodReferences18, 2, allMethods18, 2, NULL, 0, NULL, 0},
    // 19: java/lang/Object$Monitor
    {NULL, 0, NULL, 0, NULL, 0, allFields19, 3},
    // 20: java/lang/Object$WaitElement
    {NULL, 0, NULL, 0, NULL, 0, allFields20, 2},
    // 21: java/lang/OutOfMemoryError
    {allMethodReferences21, 2, allMethods21, 3, allFieldReferences21, 1, allFields21, 1},
    // 22: java/lang/Runnable
    {NULL, 0, allMethods22, 1, NULL, 0, NULL, 0},
    // 23: java/lang/RuntimeException
    {allMethodReferences23, 2, allMethods23, 2, NULL, 0, NULL, 0},
    // 24: java/lang/String
    {allMethodReferences24, 2, allMethods24, 6, allFieldReferences24, 1, allFields24, 1},
    // 25: java/lang/StringBuilder
    {allMethodReferences25, 6, allMethods25, 4, allFieldReferences25, 1, allFields25, 1},
    // 26: java/lang/System
    {allMethodReferences26, 1, allMethods26, 1, allFieldReferences26, 2, allFields26, 2},
    // 27: java/lang/Thread
    {allMethodReferences27, 8, allMethods27, 7, allFieldReferences27, 6, allFields27, 9},
    // 28: java/lang/Throwable
    {allMethodReferences28, 12, allMethods28, 6, allFieldReferences28, 3, allFields28, 2},
    // 29: java/lang/VirtualMachineError
    {allMethodReferences29, 1, allMethods29, 1, NULL, 0, NULL, 0},
    // 30: java/util/Arrays
    {NULL, 0, allMethods30, 1, NULL, 0, NULL, 0},
    // 31: thinj/regression/AllTests
    {allMethodReferences31, 7, allMethods31, 2, allFieldReferences31, 1, NULL, 0},
    // 32: thinj/regression/ThreadTest
    {allMethodReferences32, 9, allMethods32, 4, allFieldReferences32, 5, allFields32, 4},
    // 33: thinj/util/SimpleList
    {NULL, 0, NULL, 0, NULL, 0, allFields33, 1},
    // 34: thinj/util/SimpleList$Element
    {NULL, 0, NULL, 0, NULL, 0, allFields34, 2},
};

//------------------------------------------------------------------------------
// Startup information
//------------------------------------------------------------------------------

const u2 startClassIndex = 31;
const codeIndex startAddress = 0x041d;
