
//------------------------------------------------------------------------------
// Class Instance Information
//------------------------------------------------------------------------------
#define C__B 1
#define C__C 2
#define C__I 3
#define C__J 4
#define C__L_I 5
#define C__L_Ljava_lang_Object 6
#define C__L_Lthinj_regression_checkcast_CheckCast 7
#define C__Ljava_lang_Class 8
#define C__Ljava_lang_Object 9
#define C__Ljava_lang_String 10
#define C__Ljava_lang_Thread 11
#define C__Lthinj_regression_arrays_DummyClass 12
#define C__Lthinj_regression_arrays_MultiArrayTest 13
#define C__Lthinj_regression_checkcast_CheckCast 14
#define C__Z 15
#define C_java_io_PrintStream 16
#define C_java_lang_Error 21
#define C_java_lang_Exception 22
#define C_java_lang_IllegalArgumentException 23
#define C_java_lang_IllegalThreadStateException 25
#define C_java_lang_IndexOutOfBoundsException 26
#define C_java_lang_Runnable 33
#define C_java_lang_RuntimeException 34
#define C_java_lang_StringBuilder 36
#define C_java_lang_System 37
#define C_java_lang_Throwable 39
#define C_java_lang_VirtualMachineError 40
#define C_java_util_Arrays 41
#define C_thinj_regression_AllTests 42
#define C_thinj_regression_BaseClass 43
#define C_thinj_regression_ByteTest 44
#define C_thinj_regression_CharTest 45
#define C_thinj_regression_ClassTest 46
#define C_thinj_regression_DivMod 47
#define C_thinj_regression_EqualsTest 48
#define C_thinj_regression_ExtendedBaseClass 49
#define C_thinj_regression_Ineg 50
#define C_thinj_regression_InstanceAttributes 51
#define C_thinj_regression_InstanceMethods 52
#define C_thinj_regression_InstanceMethodsSpecial 53
#define C_thinj_regression_InstanceSubclassing 54
#define C_thinj_regression_LongTest 55
#define C_thinj_regression_LongTest_LinkObject 56
#define C_thinj_regression_LongTest_MyClass 57
#define C_thinj_regression_NativeTest 58
#define C_thinj_regression_ObjectTest 59
#define C_thinj_regression_Regression 60
#define C_thinj_regression_StaticInnerClassTest 61
#define C_thinj_regression_StaticInnerClassTest_Dims 62
#define C_thinj_regression_StaticInstanceAndMethod 63
#define C_thinj_regression_SystemTimeTest 64
#define C_thinj_regression_ThreadTest 65
#define C_thinj_regression_ThreadTest_1 66
#define C_thinj_regression_ThreadTest_10 67
#define C_thinj_regression_ThreadTest_11 68
#define C_thinj_regression_ThreadTest_12 69
#define C_thinj_regression_ThreadTest_13 70
#define C_thinj_regression_ThreadTest_14 71
#define C_thinj_regression_ThreadTest_15 72
#define C_thinj_regression_ThreadTest_16 73
#define C_thinj_regression_ThreadTest_17 74
#define C_thinj_regression_ThreadTest_18 75
#define C_thinj_regression_ThreadTest_19 76
#define C_thinj_regression_ThreadTest_2 77
#define C_thinj_regression_ThreadTest_20 78
#define C_thinj_regression_ThreadTest_21 79
#define C_thinj_regression_ThreadTest_22 80
#define C_thinj_regression_ThreadTest_23 81
#define C_thinj_regression_ThreadTest_24 82
#define C_thinj_regression_ThreadTest_3 83
#define C_thinj_regression_ThreadTest_4 84
#define C_thinj_regression_ThreadTest_5 85
#define C_thinj_regression_ThreadTest_6 86
#define C_thinj_regression_ThreadTest_7 87
#define C_thinj_regression_ThreadTest_8 88
#define C_thinj_regression_ThreadTest_9 89
#define C_thinj_regression_abstractclass_AbstractClass 90
#define C_thinj_regression_abstractclass_ExtendingClass 91
#define C_thinj_regression_arrays_ArrayTest 92
#define C_thinj_regression_arrays_DummyClass 93
#define C_thinj_regression_arrays_MultiArrayTest 94
#define C_thinj_regression_arrays_Sudoku 95
#define C_thinj_regression_checkcast_CheckCast 96
#define C_thinj_regression_checkcast_CheckCast_1 97
#define C_thinj_regression_checkcast_CheckCast_ClassA 98
#define C_thinj_regression_checkcast_CheckCast_ClassB 99
#define C_thinj_regression_checkcast_CheckCast_IA 100
#define C_thinj_regression_exceptions_ExIALOAD 101
#define C_thinj_regression_exceptions_ExIALOAD_LinkObject 102
#define C_thinj_regression_exceptions_ExIALOAD_MyInterface 103
#define C_thinj_regression_exceptions_ExceptionProxying 104
#define C_thinj_regression_exceptions_TestNullPointerException 105
#define C_thinj_regression_exceptions_ThrowException 106
#define C_thinj_regression_gc_GC 107
#define C_thinj_regression_gc_GC_LinkObject 108
#define C_thinj_regression_gc_HeapTest 109
#define C_thinj_regression_interfaces_AnInterface 110
#define C_thinj_regression_interfaces_AnInterfaceImpl 111
#define C_thinj_regression_interfaces_AnotherInterface 112

//------------------------------------------------------------------------------
// Class referenced by VM
//------------------------------------------------------------------------------
extern const u2 C_java_lang_ArithmeticException;
extern const u2 C_java_lang_ArrayIndexOutOfBoundsException;
extern const u2 C_java_lang_Class;
extern const u2 C_java_lang_ClassCastException;
extern const u2 C_java_lang_IllegalMonitorStateException;
extern const u2 C_java_lang_InterruptedException;
extern const u2 C_java_lang_NegativeArraySizeException;
extern const u2 C_java_lang_NullPointerException;
extern const u2 C_java_lang_Object;
extern const u2 C_java_lang_Object_Monitor;
extern const u2 C_java_lang_Object_WaitElement;
extern const u2 C_java_lang_OutOfMemoryError;
extern const u2 C_java_lang_String;
extern const u2 C_java_lang_Thread;
extern const u2 C_thinj_util_SimpleList;
extern const u2 C_thinj_util_SimpleList_Element;

//------------------------------------------------------------------------------
// Link Ids referenced by VM
//------------------------------------------------------------------------------
extern const u2 M_java_lang_ArithmeticException__init_Ljava_lang_String;
extern const u2 M_java_lang_ArrayIndexOutOfBoundsException__init_I;
extern const u2 A_java_lang_Class_aAllClasses;
extern const u2 A_java_lang_Class_aClassId;
extern const u2 A_java_lang_Class_aGlobalRefList;
extern const u2 M_java_lang_ClassCastException__init;
extern const u2 M_java_lang_IllegalMonitorStateException__init_Ljava_lang_String;
extern const u2 M_java_lang_InterruptedException__init;
extern const u2 M_java_lang_NegativeArraySizeException__init;
extern const u2 M_java_lang_NullPointerException__init;
extern const u2 A_java_lang_Object_aMonitor;
extern const u2 A_java_lang_Object_Monitor_aLockCount;
extern const u2 A_java_lang_Object_Monitor_aOwner;
extern const u2 A_java_lang_Object_Monitor_aWaitSet;
extern const u2 A_java_lang_Object_WaitElement_aNext;
extern const u2 A_java_lang_Object_WaitElement_aWaiting;
extern const u2 M_java_lang_OutOfMemoryError__init;
extern const u2 M_java_lang_OutOfMemoryError_getInstance;
extern const u2 A_java_lang_String_value;
extern const u2 A_java_lang_Thread_aBlockingObject;
extern const u2 A_java_lang_Thread_aId;
extern const u2 A_java_lang_Thread_aInterrupted;
extern const u2 A_java_lang_Thread_aLockCount;
extern const u2 A_java_lang_Thread_aState;
extern const u2 A_java_lang_Thread_aWakeUpAt;
extern const u2 M_java_lang_Thread_runFromNative;
extern const u2 A_thinj_util_SimpleList_aList;
extern const u2 A_thinj_util_SimpleList_Element_aNext;
extern const u2 A_thinj_util_SimpleList_Element_aValue;
#define A_java_lang_OutOfMemoryError_INSTANCE 27
#define A_java_lang_StringBuilder_aValue 79
#define A_java_lang_System_err 34
#define A_java_lang_System_out 74
#define A_java_lang_Thread_aRunnable 47
#define A_java_lang_Thread_aThreadIdGenerator 48
#define A_java_lang_Throwable_aCause 30
#define A_java_lang_Throwable_aStackTrace 32
#define A_thinj_regression_DivMod_tusind 144
#define A_thinj_regression_InstanceAttributes_aValue 101
#define A_thinj_regression_InstanceAttributes_aEnabled 102
#define A_thinj_regression_InstanceAttributes_aObject 103
#define A_thinj_regression_InstanceAttributes_aStaticDims 105
#define A_thinj_regression_InstanceSubclassing_aAttr 106
#define A_thinj_regression_LongTest_aIdGenerator 201
#define A_thinj_regression_LongTest_cLong 202
#define A_thinj_regression_LongTest_LinkObject_aId 49
#define A_thinj_regression_LongTest_LinkObject_aNext 207
#define A_thinj_regression_LongTest_LinkObject_aGenerator 208
#define A_thinj_regression_LongTest_MyClass_aI 204
#define A_thinj_regression_LongTest_MyClass_aJ 205
#define A_thinj_regression_LongTest_MyClass_aB 206
#define A_thinj_regression_StaticInnerClassTest_ST 140
#define A_thinj_regression_StaticInstanceAndMethod_aFoobar 94
#define A_thinj_regression_ThreadTest_aCount2 210
#define A_thinj_regression_ThreadTest_aMutex 211
#define A_thinj_regression_ThreadTest_aFlag 213
#define A_thinj_regression_ThreadTest_aDone 214
#define A_thinj_regression_ThreadTest_aCount1 215
#define A_thinj_regression_ThreadTest_1_val_mutex2 252
#define A_thinj_regression_ThreadTest_1_val_mutex1 253
#define A_thinj_regression_ThreadTest_11_val_mutex 249
#define A_thinj_regression_ThreadTest_12_val_mutex 249
#define A_thinj_regression_ThreadTest_2_val_mutex2 252
#define A_thinj_regression_ThreadTest_21_val_localMutex 251
#define A_thinj_regression_ThreadTest_4_val_mutex 249
#define A_thinj_regression_ThreadTest_7_val_mutex 249
#define A_thinj_regression_ThreadTest_8_val_mutex 249
#define A_thinj_regression_ThreadTest_8_val_t2 250
#define A_thinj_regression_ThreadTest_9_val_mutex 249
#define A_thinj_regression_abstractclass_AbstractClass_aValue 101
#define A_thinj_regression_arrays_ArrayTest_aValues 124
#define A_thinj_regression_arrays_MultiArrayTest_dims 125
#define A_thinj_regression_arrays_Sudoku_count 129
#define A_thinj_regression_exceptions_ExIALOAD_x 121
#define A_thinj_regression_exceptions_ExIALOAD_LinkObject_aPayload 136
#define A_thinj_regression_exceptions_ExIALOAD_LinkObject_aNext 181
#define A_thinj_regression_exceptions_TestNullPointerException_aUncaughtTest1 156
#define A_thinj_regression_exceptions_TestNullPointerException_aUncaughtTest2 157
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest6 150
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest7_2 152
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest7_1 153
#define A_thinj_regression_gc_GC_LinkObject_aNext 135
#define A_thinj_regression_gc_GC_LinkObject_aPayload 136
#define A_thinj_regression_interfaces_AnInterfaceImpl_y 123

//------------------------------------------------------------------------------
// Method Attributes
//------------------------------------------------------------------------------
#define M_java_lang_Object_waitJ 1
#define M_java_lang_Object__init 2
#define M_java_lang_Object_getClass 3
#define M_java_lang_Object_toString 7
#define M_java_lang_Object_hashCode 16
#define M_java_lang_Object_equalsLjava_lang_Object 17
#define M_java_lang_Object_notifyAll 19
#define M_java_lang_Object_notify 20
#define M_java_lang_Object_wait 21
#define M_java_io_PrintStream__init 2
#define M_java_io_PrintStream_printLjava_lang_Object 35
#define M_java_io_PrintStream_printlnLjava_lang_String 36
#define M_java_io_PrintStream_printLjava_lang_String 37
#define M_java_io_PrintStream_printI 38
#define M_java_io_PrintStream_outStringLfLjava_lang_String 83
#define M_java_io_PrintStream_outStringLjava_lang_String 84
#define M_java_io_PrintStream_println 86
#define M_java_lang_Class_getName 4
#define M_java_lang_Class_toString 7
#define M_java_lang_Error__init 2
#define M_java_lang_Exception__init 2
#define M_java_lang_Exception__init_Ljava_lang_String 25
#define M_java_lang_IllegalArgumentException__init_Ljava_lang_String 25
#define M_java_lang_IllegalThreadStateException__init_Ljava_lang_String 25
#define M_java_lang_IndexOutOfBoundsException__init_Ljava_lang_String 25
#define M_java_lang_NullPointerException__init_Ljava_lang_String 25
#define M_java_lang_OutOfMemoryError__clinit 29
#define M_java_lang_Runnable_run 45
#define M_java_lang_RuntimeException__init 2
#define M_java_lang_RuntimeException__init_Ljava_lang_String 25
#define M_java_lang_String_toString 7
#define M_java_lang_String__init__CII 10
#define M_java_lang_String__init__C 11
#define M_java_lang_String_length 12
#define M_java_lang_String_getCharsII_CI 15
#define M_java_lang_String_hashCode 16
#define M_java_lang_String_equalsLjava_lang_Object 17
#define M_java_lang_StringBuilder__init 2
#define M_java_lang_StringBuilder_appendLjava_lang_String 5
#define M_java_lang_StringBuilder_toString 7
#define M_java_lang_StringBuilder_appendI 18
#define M_java_lang_StringBuilder_appendJ 78
#define M_java_lang_StringBuilder_appendLjava_lang_Object 80
#define M_java_lang_StringBuilder_appendZ 81
#define M_java_lang_System__clinit 29
#define M_java_lang_System_nanoTime 75
#define M_java_lang_System_currentTimeMillis 82
#define M_java_lang_Thread__init 2
#define M_java_lang_Thread__clinit 29
#define M_java_lang_Thread_run 45
#define M_java_lang_Thread__init_Ljava_lang_Runnable 46
#define M_java_lang_Thread_attach 53
#define M_java_lang_Thread_yield 54
#define M_java_lang_Thread_start 65
#define M_java_lang_Thread_currentThread 68
#define M_java_lang_Thread_interrupt 69
#define M_java_lang_Thread_sleepJ 70
#define M_java_lang_Throwable__init 2
#define M_java_lang_Throwable_toString 7
#define M_java_lang_Throwable__init_Ljava_lang_String 25
#define M_java_lang_Throwable_getStackTraceDepth 31
#define M_java_lang_Throwable_getStackTraceElementI 33
#define M_java_lang_Throwable_printStackTrace 39
#define M_java_lang_VirtualMachineError__init 2
#define M_java_util_Arrays_hashCode_C 8
#define M_java_util_Arrays_equals_C_C 9
#define M_thinj_regression_AllTests_main_Ljava_lang_String 77
#define M_thinj_regression_AllTests__jvminit 254
#define M_thinj_regression_BaseClass__init 2
#define M_thinj_regression_BaseClass_foobar 112
#define M_thinj_regression_BaseClass_barfoo 113
#define M_thinj_regression_BaseClass_adderI 114
#define M_thinj_regression_ByteTest_main 76
#define M_thinj_regression_ByteTest_test1 96
#define M_thinj_regression_ByteTest_test2 108
#define M_thinj_regression_ByteTest_test3 109
#define M_thinj_regression_ByteTest_dimsB 146
#define M_thinj_regression_ByteTest_dimsa_B 147
#define M_thinj_regression_CharTest_main 76
#define M_thinj_regression_CharTest_test1 96
#define M_thinj_regression_CharTest_test2 108
#define M_thinj_regression_CharTest_dimsC 137
#define M_thinj_regression_CharTest_dimsa_C 138
#define M_thinj_regression_ClassTest__init 2
#define M_thinj_regression_ClassTest_main 76
#define M_thinj_regression_ClassTest_test1 96
#define M_thinj_regression_DivMod__clinit 29
#define M_thinj_regression_DivMod_main 76
#define M_thinj_regression_DivMod_test1 96
#define M_thinj_regression_DivMod_helperII 145
#define M_thinj_regression_EqualsTest__init 2
#define M_thinj_regression_EqualsTest_main 76
#define M_thinj_regression_ExtendedBaseClass__init 2
#define M_thinj_regression_ExtendedBaseClass_main 76
#define M_thinj_regression_ExtendedBaseClass_test1 96
#define M_thinj_regression_ExtendedBaseClass_test2 108
#define M_thinj_regression_ExtendedBaseClass_test3 109
#define M_thinj_regression_ExtendedBaseClass_foobar 112
#define M_thinj_regression_ExtendedBaseClass_test4 115
#define M_thinj_regression_ExtendedBaseClass_test5 116
#define M_thinj_regression_ExtendedBaseClass_test6 117
#define M_thinj_regression_ExtendedBaseClass_test7 118
#define M_thinj_regression_Ineg_main 76
#define M_thinj_regression_Ineg_test1 96
#define M_thinj_regression_Ineg_test2 108
#define M_thinj_regression_Ineg_test3 109
#define M_thinj_regression_InstanceAttributes__init 2
#define M_thinj_regression_InstanceAttributes__clinit 29
#define M_thinj_regression_InstanceAttributes_main 76
#define M_thinj_regression_InstanceAttributes_test1 96
#define M_thinj_regression_InstanceAttributes_testNull 104
#define M_thinj_regression_InstanceMethods__init 2
#define M_thinj_regression_InstanceMethods_main 76
#define M_thinj_regression_InstanceMethods_test1 96
#define M_thinj_regression_InstanceMethods_testargsIZ 107
#define M_thinj_regression_InstanceMethods_test2 108
#define M_thinj_regression_InstanceMethods_test3 109
#define M_thinj_regression_InstanceMethods_basePrintI 110
#define M_thinj_regression_InstanceMethods_basePrint2 111
#define M_thinj_regression_InstanceMethodsSpecial__init 2
#define M_thinj_regression_InstanceMethodsSpecial_main 76
#define M_thinj_regression_InstanceMethodsSpecial_testargsIZ 107
#define M_thinj_regression_InstanceMethodsSpecial_basePrint2 111
#define M_thinj_regression_InstanceSubclassing__init 2
#define M_thinj_regression_InstanceSubclassing_main 76
#define M_thinj_regression_InstanceSubclassing_test1 96
#define M_thinj_regression_LongTest__clinit 29
#define M_thinj_regression_LongTest_main 76
#define M_thinj_regression_LongTest_test1 96
#define M_thinj_regression_LongTest_test2 108
#define M_thinj_regression_LongTest_test3 109
#define M_thinj_regression_LongTest_test4 115
#define M_thinj_regression_LongTest_test5 116
#define M_thinj_regression_LongTest_test6 117
#define M_thinj_regression_LongTest_test7 118
#define M_thinj_regression_LongTest_test8 183
#define M_thinj_regression_LongTest_test9 184
#define M_thinj_regression_LongTest_heapTest 185
#define M_thinj_regression_LongTest_test10 186
#define M_thinj_regression_LongTest_test11 187
#define M_thinj_regression_LongTest_test12 188
#define M_thinj_regression_LongTest_test13 189
#define M_thinj_regression_LongTest_test14 190
#define M_thinj_regression_LongTest_test7_1ZJI 191
#define M_thinj_regression_LongTest_test8_1 192
#define M_thinj_regression_LongTest_LinkObject__clinit 29
#define M_thinj_regression_LongTest_LinkObject_consumeHeap 200
#define M_thinj_regression_LongTest_LinkObject__init_Lthinj_regression_LongTest_LinkObject 209
#define M_thinj_regression_LongTest_MyClass__init 2
#define M_thinj_regression_LongTest_MyClass__init_Lthinj_regression_LongTest_1 193
#define M_thinj_regression_LongTest_MyClass_access_102Lthinj_regression_LongTest_MyClass_Z 194
#define M_thinj_regression_LongTest_MyClass_access_202Lthinj_regression_LongTest_MyClass_J 195
#define M_thinj_regression_LongTest_MyClass_access_302Lthinj_regression_LongTest_MyClass_I 196
#define M_thinj_regression_LongTest_MyClass_access_100Lthinj_regression_LongTest_MyClass 197
#define M_thinj_regression_LongTest_MyClass_access_200Lthinj_regression_LongTest_MyClass 198
#define M_thinj_regression_LongTest_MyClass_access_300Lthinj_regression_LongTest_MyClass 199
#define M_thinj_regression_NativeTest_main 76
#define M_thinj_regression_ObjectTest_main 76
#define M_thinj_regression_ObjectTest_test1 96
#define M_thinj_regression_Regression_verifyZ 92
#define M_thinj_regression_StaticInnerClassTest__clinit 29
#define M_thinj_regression_StaticInnerClassTest_main 76
#define M_thinj_regression_StaticInnerClassTest_Dims__init 2
#define M_thinj_regression_StaticInnerClassTest_Dims__init_Lthinj_regression_StaticInnerClassTest_1 139
#define M_thinj_regression_StaticInstanceAndMethod__clinit 29
#define M_thinj_regression_StaticInstanceAndMethod_main 76
#define M_thinj_regression_StaticInstanceAndMethod_facultyI 93
#define M_thinj_regression_StaticInstanceAndMethod_ThisTestShallFail 95
#define M_thinj_regression_StaticInstanceAndMethod_test1 96
#define M_thinj_regression_StaticInstanceAndMethod_test2 97
#define M_thinj_regression_SystemTimeTest_main_Ljava_lang_String 77
#define M_thinj_regression_ThreadTest__clinit 29
#define M_thinj_regression_ThreadTest_main_Ljava_lang_String 77
#define M_thinj_regression_ThreadTest_test3 109
#define M_thinj_regression_ThreadTest_test4 115
#define M_thinj_regression_ThreadTest_test5 116
#define M_thinj_regression_ThreadTest_test6 117
#define M_thinj_regression_ThreadTest_test7 118
#define M_thinj_regression_ThreadTest_test8 183
#define M_thinj_regression_ThreadTest_test10 186
#define M_thinj_regression_ThreadTest_test11 187
#define M_thinj_regression_ThreadTest_test12 188
#define M_thinj_regression_ThreadTest_test13 189
#define M_thinj_regression_ThreadTest_busyWaitJ 212
#define M_thinj_regression_ThreadTest_testWait 216
#define M_thinj_regression_ThreadTest_simpleYield 217
#define M_thinj_regression_ThreadTest_yieldAndGCMainThread 218
#define M_thinj_regression_ThreadTest_yieldAndGCNewThread 219
#define M_thinj_regression_ThreadTest_testAutoYield 220
#define M_thinj_regression_ThreadTest_threadGC 221
#define M_thinj_regression_ThreadTest_testExplicitYield 222
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_0 223
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_2 224
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_1 225
#define M_thinj_regression_ThreadTest_test2_1 226
#define M_thinj_regression_ThreadTest_test2_2 227
#define M_thinj_regression_ThreadTest_test2_3 228
#define M_thinj_regression_ThreadTest_test2_4 229
#define M_thinj_regression_ThreadTest_test8_1 230
#define M_thinj_regression_ThreadTest_test9_1 231
#define M_thinj_regression_ThreadTest_test9_2 232
#define M_thinj_regression_ThreadTest_busyWaitDoneJ 235
#define M_thinj_regression_ThreadTest_test9_helper1 237
#define M_thinj_regression_ThreadTest_test9_helper2 238
#define M_thinj_regression_ThreadTest_access_008 239
#define M_thinj_regression_ThreadTest_access_000 240
#define M_thinj_regression_ThreadTest_access_102Z 241
#define M_thinj_regression_ThreadTest_access_200 242
#define M_thinj_regression_ThreadTest_access_300J 243
#define M_thinj_regression_ThreadTest_access_202Z 244
#define M_thinj_regression_ThreadTest_access_100 245
#define M_thinj_regression_ThreadTest_access_400 246
#define M_thinj_regression_ThreadTest_access_508 247
#define M_thinj_regression_ThreadTest_access_500 248
#define M_thinj_regression_ThreadTest_1_run 45
#define M_thinj_regression_ThreadTest_1__init_Ljava_lang_Object_Ljava_lang_Object 233
#define M_thinj_regression_ThreadTest_10__init 2
#define M_thinj_regression_ThreadTest_10_run 45
#define M_thinj_regression_ThreadTest_11_run 45
#define M_thinj_regression_ThreadTest_11__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_12_run 45
#define M_thinj_regression_ThreadTest_12__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_13__init 2
#define M_thinj_regression_ThreadTest_13_run 45
#define M_thinj_regression_ThreadTest_14__init 2
#define M_thinj_regression_ThreadTest_14_run 45
#define M_thinj_regression_ThreadTest_15__init 2
#define M_thinj_regression_ThreadTest_15_run 45
#define M_thinj_regression_ThreadTest_16__init 2
#define M_thinj_regression_ThreadTest_16_run 45
#define M_thinj_regression_ThreadTest_17__init 2
#define M_thinj_regression_ThreadTest_17_run 45
#define M_thinj_regression_ThreadTest_18__init 2
#define M_thinj_regression_ThreadTest_18_run 45
#define M_thinj_regression_ThreadTest_19__init 2
#define M_thinj_regression_ThreadTest_19_run 45
#define M_thinj_regression_ThreadTest_2_run 45
#define M_thinj_regression_ThreadTest_2__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_20__init 2
#define M_thinj_regression_ThreadTest_20_run 45
#define M_thinj_regression_ThreadTest_21_run 45
#define M_thinj_regression_ThreadTest_21__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_22__init 2
#define M_thinj_regression_ThreadTest_22_run 45
#define M_thinj_regression_ThreadTest_23__init 2
#define M_thinj_regression_ThreadTest_23_run 45
#define M_thinj_regression_ThreadTest_24__init 2
#define M_thinj_regression_ThreadTest_24_run 45
#define M_thinj_regression_ThreadTest_3__init 2
#define M_thinj_regression_ThreadTest_3_run 45
#define M_thinj_regression_ThreadTest_4_run 45
#define M_thinj_regression_ThreadTest_4__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_5__init 2
#define M_thinj_regression_ThreadTest_5_run 45
#define M_thinj_regression_ThreadTest_6__init 2
#define M_thinj_regression_ThreadTest_6_run 45
#define M_thinj_regression_ThreadTest_7_run 45
#define M_thinj_regression_ThreadTest_7__init_Ljava_lang_Object 234
#define M_thinj_regression_ThreadTest_8_run 45
#define M_thinj_regression_ThreadTest_8__init_Ljava_lang_Object_Ljava_lang_Thread 236
#define M_thinj_regression_ThreadTest_9_run 45
#define M_thinj_regression_ThreadTest_9__init_Ljava_lang_Object 234
#define M_thinj_regression_abstractclass_AbstractClass__init_I 26
#define M_thinj_regression_abstractclass_AbstractClass_main 76
#define M_thinj_regression_abstractclass_AbstractClass_test1 96
#define M_thinj_regression_abstractclass_AbstractClass_test2 108
#define M_thinj_regression_abstractclass_AbstractClass_foobar 119
#define M_thinj_regression_abstractclass_ExtendingClass__init_I 26
#define M_thinj_regression_abstractclass_ExtendingClass_foobar 119
#define M_thinj_regression_arrays_ArrayTest__init 2
#define M_thinj_regression_arrays_ArrayTest_main 76
#define M_thinj_regression_arrays_ArrayTest_test1 96
#define M_thinj_regression_arrays_ArrayTest_test2 108
#define M_thinj_regression_arrays_DummyClass__clinit 29
#define M_thinj_regression_arrays_DummyClass_cyclicDependency 126
#define M_thinj_regression_arrays_MultiArrayTest__clinit 29
#define M_thinj_regression_arrays_MultiArrayTest_main 76
#define M_thinj_regression_arrays_MultiArrayTest_test1 96
#define M_thinj_regression_arrays_MultiArrayTest_test2 108
#define M_thinj_regression_arrays_MultiArrayTest_test3 109
#define M_thinj_regression_arrays_Sudoku__clinit 29
#define M_thinj_regression_arrays_Sudoku_main 76
#define M_thinj_regression_arrays_Sudoku_solve__II 130
#define M_thinj_regression_arrays_Sudoku_getUsedValues__III 131
#define M_thinj_regression_checkcast_CheckCast_main 76
#define M_thinj_regression_checkcast_CheckCast_test1 96
#define M_thinj_regression_checkcast_CheckCast_test2 108
#define M_thinj_regression_checkcast_CheckCast_test3 109
#define M_thinj_regression_checkcast_CheckCast_test4 115
#define M_thinj_regression_checkcast_CheckCast_multitestLjava_lang_Object 142
#define M_thinj_regression_checkcast_CheckCast_1__init 2
#define M_thinj_regression_checkcast_CheckCast_ClassA__init 2
#define M_thinj_regression_checkcast_CheckCast_ClassB__init 2
#define M_thinj_regression_exceptions_ExIALOAD_main 76
#define M_thinj_regression_exceptions_ExIALOAD_get 122
#define M_thinj_regression_exceptions_ExIALOAD_getI 158
#define M_thinj_regression_exceptions_ExIALOAD_iaload 160
#define M_thinj_regression_exceptions_ExIALOAD_aaload 161
#define M_thinj_regression_exceptions_ExIALOAD_baload 162
#define M_thinj_regression_exceptions_ExIALOAD_caload 163
#define M_thinj_regression_exceptions_ExIALOAD_iastore 164
#define M_thinj_regression_exceptions_ExIALOAD_aastore 165
#define M_thinj_regression_exceptions_ExIALOAD_bastore 166
#define M_thinj_regression_exceptions_ExIALOAD_castore 167
#define M_thinj_regression_exceptions_ExIALOAD_idiv 168
#define M_thinj_regression_exceptions_ExIALOAD_irem 169
#define M_thinj_regression_exceptions_ExIALOAD_getfield 170
#define M_thinj_regression_exceptions_ExIALOAD_putfield 171
#define M_thinj_regression_exceptions_ExIALOAD_invokespecial 172
#define M_thinj_regression_exceptions_ExIALOAD_invokevirtual 173
#define M_thinj_regression_exceptions_ExIALOAD_invokeinterface 174
#define M_thinj_regression_exceptions_ExIALOAD_test_new 175
#define M_thinj_regression_exceptions_ExIALOAD_newarray 176
#define M_thinj_regression_exceptions_ExIALOAD_anewarray 177
#define M_thinj_regression_exceptions_ExIALOAD_arraylength 178
#define M_thinj_regression_exceptions_ExIALOAD_athrow 179
#define M_thinj_regression_exceptions_ExIALOAD_checkcast 180
#define M_thinj_regression_exceptions_ExIALOAD_LinkObject_consumeHeapI 159
#define M_thinj_regression_exceptions_ExIALOAD_LinkObject__init_Lthinj_regression_exceptions_ExIALOAD_LinkObject_I 182
#define M_thinj_regression_exceptions_ExIALOAD_MyInterface_foobar 119
#define M_thinj_regression_exceptions_ExceptionProxying_testExceptionProxy 149
#define M_thinj_regression_exceptions_TestNullPointerException_main 76
#define M_thinj_regression_exceptions_TestNullPointerException_test1 96
#define M_thinj_regression_exceptions_TestNullPointerException_test2 108
#define M_thinj_regression_exceptions_ThrowException_main 76
#define M_thinj_regression_exceptions_ThrowException_test1 96
#define M_thinj_regression_exceptions_ThrowException_test2 108
#define M_thinj_regression_exceptions_ThrowException_test3 109
#define M_thinj_regression_exceptions_ThrowException_test4 115
#define M_thinj_regression_exceptions_ThrowException_test5 116
#define M_thinj_regression_exceptions_ThrowException_test6 117
#define M_thinj_regression_exceptions_ThrowException_test7 118
#define M_thinj_regression_exceptions_ThrowException_testHelper 148
#define M_thinj_regression_exceptions_ThrowException_test6Helper 151
#define M_thinj_regression_exceptions_ThrowException_test7Helper2 154
#define M_thinj_regression_exceptions_ThrowException_test7Helper1 155
#define M_thinj_regression_gc_GC_main 76
#define M_thinj_regression_gc_GC_circularObjects 134
#define M_thinj_regression_gc_GC_LinkObject__init_I 26
#define M_thinj_regression_gc_GC_LinkObject_access_002Lthinj_regression_gc_GC_LinkObject_Lthinj_regression_gc_GC_LinkObject 132
#define M_thinj_regression_gc_GC_LinkObject_access_000Lthinj_regression_gc_GC_LinkObject 133
#define M_thinj_regression_gc_HeapTest_main 76
#define M_thinj_regression_gc_HeapTest_test1 96
#define M_thinj_regression_gc_HeapTest_test2 108
#define M_thinj_regression_gc_HeapTest_test0 141
#define M_thinj_regression_interfaces_AnInterface_foobar 119
#define M_thinj_regression_interfaces_AnInterface_get 122
#define M_thinj_regression_interfaces_AnInterfaceImpl__init 2
#define M_thinj_regression_interfaces_AnInterfaceImpl_main 76
#define M_thinj_regression_interfaces_AnInterfaceImpl_test1 96
#define M_thinj_regression_interfaces_AnInterfaceImpl_foobar 119
#define M_thinj_regression_interfaces_AnInterfaceImpl_getLost 120
#define M_thinj_regression_interfaces_AnInterfaceImpl_get 122
#define M_thinj_regression_interfaces_AnotherInterface_getLost 120
