
//------------------------------------------------------------------------------
// Class Instance Information
//------------------------------------------------------------------------------
#define C__B 1
#define C__C 2
#define C__I 3
#define C__J 4
#define C__L_I 5
#define C__L_Ljava_lang_Object 6
#define C__L_Lthinj_regression_checkcast_CheckCast 7
#define C__Ljava_lang_Class 8
#define C__Ljava_lang_Object 9
#define C__Ljava_lang_String 10
#define C__Ljava_lang_Thread 11
#define C__Lthinj_regression_arrays_DummyClass 12
#define C__Lthinj_regression_arrays_MultiArrayTest 13
#define C__Lthinj_regression_checkcast_CheckCast 14
#define C__Z 15
#define C_java_io_PrintStream 16
#define C_java_lang_Error 21
#define C_java_lang_Exception 22
#define C_java_lang_IllegalArgumentException 23
#define C_java_lang_IllegalThreadStateException 25
#define C_java_lang_IndexOutOfBoundsException 26
#define C_java_lang_Runnable 33
#define C_java_lang_RuntimeException 34
#define C_java_lang_StringBuilder 36
#define C_java_lang_System 37
#define C_java_lang_Throwable 39
#define C_java_lang_VirtualMachineError 40
#define C_java_util_Arrays 41
#define C_thinj_regression_AllTests 42
#define C_thinj_regression_BaseClass 43
#define C_thinj_regression_ByteTest 44
#define C_thinj_regression_CharTest 45
#define C_thinj_regression_ClassTest 46
#define C_thinj_regression_DivMod 47
#define C_thinj_regression_EqualsTest 48
#define C_thinj_regression_ExtendedBaseClass 49
#define C_thinj_regression_Ineg 50
#define C_thinj_regression_InstanceAttributes 51
#define C_thinj_regression_InstanceMethods 52
#define C_thinj_regression_InstanceMethodsSpecial 53
#define C_thinj_regression_InstanceSubclassing 54
#define C_thinj_regression_LongTest 55
#define C_thinj_regression_LongTest_LinkObject 56
#define C_thinj_regression_LongTest_MyClass 57
#define C_thinj_regression_NativeTest 58
#define C_thinj_regression_ObjectTest 59
#define C_thinj_regression_Regression 60
#define C_thinj_regression_StaticInnerClassTest 61
#define C_thinj_regression_StaticInnerClassTest_Dims 62
#define C_thinj_regression_StaticInstanceAndMethod 63
#define C_thinj_regression_SystemTimeTest 64
#define C_thinj_regression_ThreadTest 65
#define C_thinj_regression_ThreadTest_1 66
#define C_thinj_regression_ThreadTest_10 67
#define C_thinj_regression_ThreadTest_11 68
#define C_thinj_regression_ThreadTest_12 69
#define C_thinj_regression_ThreadTest_13 70
#define C_thinj_regression_ThreadTest_14 71
#define C_thinj_regression_ThreadTest_15 72
#define C_thinj_regression_ThreadTest_16 73
#define C_thinj_regression_ThreadTest_17 74
#define C_thinj_regression_ThreadTest_18 75
#define C_thinj_regression_ThreadTest_19 76
#define C_thinj_regression_ThreadTest_2 77
#define C_thinj_regression_ThreadTest_20 78
#define C_thinj_regression_ThreadTest_3 79
#define C_thinj_regression_ThreadTest_4 80
#define C_thinj_regression_ThreadTest_5 81
#define C_thinj_regression_ThreadTest_6 82
#define C_thinj_regression_ThreadTest_7 83
#define C_thinj_regression_ThreadTest_8 84
#define C_thinj_regression_ThreadTest_9 85
#define C_thinj_regression_abstractclass_AbstractClass 86
#define C_thinj_regression_abstractclass_ExtendingClass 87
#define C_thinj_regression_arrays_ArrayTest 88
#define C_thinj_regression_arrays_DummyClass 89
#define C_thinj_regression_arrays_MultiArrayTest 90
#define C_thinj_regression_arrays_Sudoku 91
#define C_thinj_regression_checkcast_CheckCast 92
#define C_thinj_regression_checkcast_CheckCast_1 93
#define C_thinj_regression_checkcast_CheckCast_ClassA 94
#define C_thinj_regression_checkcast_CheckCast_ClassB 95
#define C_thinj_regression_checkcast_CheckCast_IA 96
#define C_thinj_regression_exceptions_ExIALOAD 97
#define C_thinj_regression_exceptions_ExIALOAD_LinkObject 98
#define C_thinj_regression_exceptions_ExIALOAD_MyInterface 99
#define C_thinj_regression_exceptions_ExceptionProxying 100
#define C_thinj_regression_exceptions_TestNullPointerException 101
#define C_thinj_regression_exceptions_ThrowException 102
#define C_thinj_regression_gc_GC 103
#define C_thinj_regression_gc_GC_LinkObject 104
#define C_thinj_regression_gc_HeapTest 105
#define C_thinj_regression_interfaces_AnInterface 106
#define C_thinj_regression_interfaces_AnInterfaceImpl 107
#define C_thinj_regression_interfaces_AnotherInterface 108

//------------------------------------------------------------------------------
// Class referenced by VM
//------------------------------------------------------------------------------
extern const u2 C_java_lang_ArithmeticException;
extern const u2 C_java_lang_ArrayIndexOutOfBoundsException;
extern const u2 C_java_lang_Class;
extern const u2 C_java_lang_ClassCastException;
extern const u2 C_java_lang_IllegalMonitorStateException;
extern const u2 C_java_lang_InterruptedException;
extern const u2 C_java_lang_NegativeArraySizeException;
extern const u2 C_java_lang_NullPointerException;
extern const u2 C_java_lang_Object;
extern const u2 C_java_lang_Object_Monitor;
extern const u2 C_java_lang_Object_WaitElement;
extern const u2 C_java_lang_OutOfMemoryError;
extern const u2 C_java_lang_String;
extern const u2 C_java_lang_Thread;
extern const u2 C_thinj_util_SimpleList;
extern const u2 C_thinj_util_SimpleList_Element;

//------------------------------------------------------------------------------
// Link Ids referenced by VM
//------------------------------------------------------------------------------
extern const u2 M_java_lang_ArithmeticException__init_Ljava_lang_String;
extern const u2 M_java_lang_ArrayIndexOutOfBoundsException__init_I;
extern const u2 A_java_lang_Class_aAllClasses;
extern const u2 A_java_lang_Class_aClassId;
extern const u2 A_java_lang_Class_aGlobalRefList;
extern const u2 M_java_lang_ClassCastException__init;
extern const u2 M_java_lang_IllegalMonitorStateException__init_Ljava_lang_String;
extern const u2 M_java_lang_InterruptedException__init;
extern const u2 M_java_lang_NegativeArraySizeException__init;
extern const u2 M_java_lang_NullPointerException__init;
extern const u2 A_java_lang_Object_aMonitor;
extern const u2 A_java_lang_Object_Monitor_aLockCount;
extern const u2 A_java_lang_Object_Monitor_aOwner;
extern const u2 A_java_lang_Object_Monitor_aWaitSet;
extern const u2 A_java_lang_Object_WaitElement_aNext;
extern const u2 A_java_lang_Object_WaitElement_aWaiting;
extern const u2 M_java_lang_OutOfMemoryError__init;
extern const u2 M_java_lang_OutOfMemoryError_getInstance;
extern const u2 A_java_lang_String_value;
extern const u2 A_java_lang_Thread_aBlockingObject;
extern const u2 A_java_lang_Thread_aCurrentThread;
extern const u2 A_java_lang_Thread_aId;
extern const u2 A_java_lang_Thread_aInterrupted;
extern const u2 A_java_lang_Thread_aLockCount;
extern const u2 A_java_lang_Thread_aState;
extern const u2 A_java_lang_Thread_aWakeUpAt;
extern const u2 M_java_lang_Thread_runFromNative;
extern const u2 A_thinj_util_SimpleList_aList;
extern const u2 A_thinj_util_SimpleList_Element_aNext;
extern const u2 A_thinj_util_SimpleList_Element_aValue;
#define A_java_lang_OutOfMemoryError_INSTANCE 26
#define A_java_lang_StringBuilder_aValue 76
#define A_java_lang_System_err 33
#define A_java_lang_System_out 71
#define A_java_lang_Thread_aRunnable 46
#define A_java_lang_Thread_aThreadIdGenerator 47
#define A_java_lang_Throwable_aCause 29
#define A_java_lang_Throwable_aStackTrace 31
#define A_thinj_regression_DivMod_tusind 141
#define A_thinj_regression_InstanceAttributes_aValue 98
#define A_thinj_regression_InstanceAttributes_aEnabled 99
#define A_thinj_regression_InstanceAttributes_aObject 100
#define A_thinj_regression_InstanceAttributes_aStaticDims 102
#define A_thinj_regression_InstanceSubclassing_aAttr 103
#define A_thinj_regression_LongTest_aIdGenerator 198
#define A_thinj_regression_LongTest_cLong 199
#define A_thinj_regression_LongTest_LinkObject_aId 48
#define A_thinj_regression_LongTest_LinkObject_aNext 204
#define A_thinj_regression_LongTest_LinkObject_aGenerator 205
#define A_thinj_regression_LongTest_MyClass_aI 201
#define A_thinj_regression_LongTest_MyClass_aJ 202
#define A_thinj_regression_LongTest_MyClass_aB 203
#define A_thinj_regression_StaticInnerClassTest_ST 137
#define A_thinj_regression_StaticInstanceAndMethod_aFoobar 91
#define A_thinj_regression_ThreadTest_aCount2 207
#define A_thinj_regression_ThreadTest_aMutex 208
#define A_thinj_regression_ThreadTest_aFlag 210
#define A_thinj_regression_ThreadTest_aDone 211
#define A_thinj_regression_ThreadTest_aCount1 212
#define A_thinj_regression_ThreadTest_4_val_mutex 239
#define A_thinj_regression_ThreadTest_5_val_mutex 239
#define A_thinj_regression_ThreadTest_5_val_t2 240
#define A_thinj_regression_ThreadTest_6_val_mutex 239
#define A_thinj_regression_ThreadTest_8_val_mutex 239
#define A_thinj_regression_ThreadTest_9_val_mutex 239
#define A_thinj_regression_abstractclass_AbstractClass_aValue 98
#define A_thinj_regression_arrays_ArrayTest_aValues 121
#define A_thinj_regression_arrays_MultiArrayTest_dims 122
#define A_thinj_regression_arrays_Sudoku_count 126
#define A_thinj_regression_exceptions_ExIALOAD_x 118
#define A_thinj_regression_exceptions_ExIALOAD_LinkObject_aPayload 133
#define A_thinj_regression_exceptions_ExIALOAD_LinkObject_aNext 178
#define A_thinj_regression_exceptions_TestNullPointerException_aUncaughtTest1 153
#define A_thinj_regression_exceptions_TestNullPointerException_aUncaughtTest2 154
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest6 147
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest7_2 149
#define A_thinj_regression_exceptions_ThrowException_aFinallyTest7_1 150
#define A_thinj_regression_gc_GC_LinkObject_aNext 132
#define A_thinj_regression_gc_GC_LinkObject_aPayload 133
#define A_thinj_regression_interfaces_AnInterfaceImpl_y 120

//------------------------------------------------------------------------------
// Method Attributes
//------------------------------------------------------------------------------
#define M_java_lang_Object__init 1
#define M_java_lang_Object_getClass 2
#define M_java_lang_Object_toString 6
#define M_java_lang_Object_hashCode 15
#define M_java_lang_Object_equalsLjava_lang_Object 16
#define M_java_lang_Object_notifyAll 18
#define M_java_lang_Object_notify 19
#define M_java_lang_Object_wait 20
#define M_java_io_PrintStream__init 1
#define M_java_io_PrintStream_printLjava_lang_Object 34
#define M_java_io_PrintStream_printlnLjava_lang_String 35
#define M_java_io_PrintStream_printLjava_lang_String 36
#define M_java_io_PrintStream_printI 37
#define M_java_io_PrintStream_outStringLfLjava_lang_String 80
#define M_java_io_PrintStream_outStringLjava_lang_String 81
#define M_java_io_PrintStream_println 83
#define M_java_lang_Class_getName 3
#define M_java_lang_Class_toString 6
#define M_java_lang_Error__init 1
#define M_java_lang_Exception__init 1
#define M_java_lang_Exception__init_Ljava_lang_String 24
#define M_java_lang_IllegalArgumentException__init_Ljava_lang_String 24
#define M_java_lang_IllegalThreadStateException__init_Ljava_lang_String 24
#define M_java_lang_IndexOutOfBoundsException__init_Ljava_lang_String 24
#define M_java_lang_NullPointerException__init_Ljava_lang_String 24
#define M_java_lang_OutOfMemoryError__clinit 28
#define M_java_lang_Runnable_run 44
#define M_java_lang_RuntimeException__init 1
#define M_java_lang_RuntimeException__init_Ljava_lang_String 24
#define M_java_lang_String_toString 6
#define M_java_lang_String__init__CII 9
#define M_java_lang_String__init__C 10
#define M_java_lang_String_length 11
#define M_java_lang_String_getCharsII_CI 14
#define M_java_lang_String_hashCode 15
#define M_java_lang_String_equalsLjava_lang_Object 16
#define M_java_lang_StringBuilder__init 1
#define M_java_lang_StringBuilder_appendLjava_lang_String 4
#define M_java_lang_StringBuilder_toString 6
#define M_java_lang_StringBuilder_appendI 17
#define M_java_lang_StringBuilder_appendJ 75
#define M_java_lang_StringBuilder_appendLjava_lang_Object 77
#define M_java_lang_StringBuilder_appendZ 78
#define M_java_lang_System__clinit 28
#define M_java_lang_System_nanoTime 72
#define M_java_lang_System_currentTimeMillis 79
#define M_java_lang_Thread__init 1
#define M_java_lang_Thread__clinit 28
#define M_java_lang_Thread_run 44
#define M_java_lang_Thread__init_Ljava_lang_Runnable 45
#define M_java_lang_Thread_attach 51
#define M_java_lang_Thread_yield 52
#define M_java_lang_Thread_start 62
#define M_java_lang_Thread_interrupt 66
#define M_java_lang_Thread_sleepJ 67
#define M_java_lang_Throwable__init 1
#define M_java_lang_Throwable_toString 6
#define M_java_lang_Throwable__init_Ljava_lang_String 24
#define M_java_lang_Throwable_getStackTraceDepth 30
#define M_java_lang_Throwable_getStackTraceElementI 32
#define M_java_lang_Throwable_printStackTrace 38
#define M_java_lang_VirtualMachineError__init 1
#define M_java_util_Arrays_hashCode_C 7
#define M_java_util_Arrays_equals_C_C 8
#define M_thinj_regression_AllTests_main_Ljava_lang_String 74
#define M_thinj_regression_AllTests__jvminit 241
#define M_thinj_regression_BaseClass__init 1
#define M_thinj_regression_BaseClass_foobar 109
#define M_thinj_regression_BaseClass_barfoo 110
#define M_thinj_regression_BaseClass_adderI 111
#define M_thinj_regression_ByteTest_main 73
#define M_thinj_regression_ByteTest_test1 93
#define M_thinj_regression_ByteTest_test2 105
#define M_thinj_regression_ByteTest_test3 106
#define M_thinj_regression_ByteTest_dimsB 143
#define M_thinj_regression_ByteTest_dimsa_B 144
#define M_thinj_regression_CharTest_main 73
#define M_thinj_regression_CharTest_test1 93
#define M_thinj_regression_CharTest_test2 105
#define M_thinj_regression_CharTest_dimsC 134
#define M_thinj_regression_CharTest_dimsa_C 135
#define M_thinj_regression_ClassTest__init 1
#define M_thinj_regression_ClassTest_main 73
#define M_thinj_regression_ClassTest_test1 93
#define M_thinj_regression_DivMod__clinit 28
#define M_thinj_regression_DivMod_main 73
#define M_thinj_regression_DivMod_test1 93
#define M_thinj_regression_DivMod_helperII 142
#define M_thinj_regression_EqualsTest__init 1
#define M_thinj_regression_EqualsTest_main 73
#define M_thinj_regression_ExtendedBaseClass__init 1
#define M_thinj_regression_ExtendedBaseClass_main 73
#define M_thinj_regression_ExtendedBaseClass_test1 93
#define M_thinj_regression_ExtendedBaseClass_test2 105
#define M_thinj_regression_ExtendedBaseClass_test3 106
#define M_thinj_regression_ExtendedBaseClass_foobar 109
#define M_thinj_regression_ExtendedBaseClass_test4 112
#define M_thinj_regression_ExtendedBaseClass_test5 113
#define M_thinj_regression_ExtendedBaseClass_test6 114
#define M_thinj_regression_ExtendedBaseClass_test7 115
#define M_thinj_regression_Ineg_main 73
#define M_thinj_regression_Ineg_test1 93
#define M_thinj_regression_Ineg_test2 105
#define M_thinj_regression_Ineg_test3 106
#define M_thinj_regression_InstanceAttributes__init 1
#define M_thinj_regression_InstanceAttributes__clinit 28
#define M_thinj_regression_InstanceAttributes_main 73
#define M_thinj_regression_InstanceAttributes_test1 93
#define M_thinj_regression_InstanceAttributes_testNull 101
#define M_thinj_regression_InstanceMethods__init 1
#define M_thinj_regression_InstanceMethods_main 73
#define M_thinj_regression_InstanceMethods_test1 93
#define M_thinj_regression_InstanceMethods_testargsIZ 104
#define M_thinj_regression_InstanceMethods_test2 105
#define M_thinj_regression_InstanceMethods_test3 106
#define M_thinj_regression_InstanceMethods_basePrintI 107
#define M_thinj_regression_InstanceMethods_basePrint2 108
#define M_thinj_regression_InstanceMethodsSpecial__init 1
#define M_thinj_regression_InstanceMethodsSpecial_main 73
#define M_thinj_regression_InstanceMethodsSpecial_testargsIZ 104
#define M_thinj_regression_InstanceMethodsSpecial_basePrint2 108
#define M_thinj_regression_InstanceSubclassing__init 1
#define M_thinj_regression_InstanceSubclassing_main 73
#define M_thinj_regression_InstanceSubclassing_test1 93
#define M_thinj_regression_LongTest__clinit 28
#define M_thinj_regression_LongTest_main 73
#define M_thinj_regression_LongTest_test1 93
#define M_thinj_regression_LongTest_test2 105
#define M_thinj_regression_LongTest_test3 106
#define M_thinj_regression_LongTest_test4 112
#define M_thinj_regression_LongTest_test5 113
#define M_thinj_regression_LongTest_test6 114
#define M_thinj_regression_LongTest_test7 115
#define M_thinj_regression_LongTest_test8 180
#define M_thinj_regression_LongTest_test9 181
#define M_thinj_regression_LongTest_heapTest 182
#define M_thinj_regression_LongTest_test10 183
#define M_thinj_regression_LongTest_test11 184
#define M_thinj_regression_LongTest_test12 185
#define M_thinj_regression_LongTest_test13 186
#define M_thinj_regression_LongTest_test14 187
#define M_thinj_regression_LongTest_test7_1ZJI 188
#define M_thinj_regression_LongTest_test8_1 189
#define M_thinj_regression_LongTest_LinkObject__clinit 28
#define M_thinj_regression_LongTest_LinkObject_consumeHeap 197
#define M_thinj_regression_LongTest_LinkObject__init_Lthinj_regression_LongTest_LinkObject 206
#define M_thinj_regression_LongTest_MyClass__init 1
#define M_thinj_regression_LongTest_MyClass__init_Lthinj_regression_LongTest_1 190
#define M_thinj_regression_LongTest_MyClass_access_102Lthinj_regression_LongTest_MyClass_Z 191
#define M_thinj_regression_LongTest_MyClass_access_202Lthinj_regression_LongTest_MyClass_J 192
#define M_thinj_regression_LongTest_MyClass_access_302Lthinj_regression_LongTest_MyClass_I 193
#define M_thinj_regression_LongTest_MyClass_access_100Lthinj_regression_LongTest_MyClass 194
#define M_thinj_regression_LongTest_MyClass_access_200Lthinj_regression_LongTest_MyClass 195
#define M_thinj_regression_LongTest_MyClass_access_300Lthinj_regression_LongTest_MyClass 196
#define M_thinj_regression_NativeTest_main 73
#define M_thinj_regression_ObjectTest_main 73
#define M_thinj_regression_ObjectTest_test1 93
#define M_thinj_regression_Regression_verifyZ 89
#define M_thinj_regression_StaticInnerClassTest__clinit 28
#define M_thinj_regression_StaticInnerClassTest_main 73
#define M_thinj_regression_StaticInnerClassTest_Dims__init 1
#define M_thinj_regression_StaticInnerClassTest_Dims__init_Lthinj_regression_StaticInnerClassTest_1 136
#define M_thinj_regression_StaticInstanceAndMethod__clinit 28
#define M_thinj_regression_StaticInstanceAndMethod_main 73
#define M_thinj_regression_StaticInstanceAndMethod_facultyI 90
#define M_thinj_regression_StaticInstanceAndMethod_ThisTestShallFail 92
#define M_thinj_regression_StaticInstanceAndMethod_test1 93
#define M_thinj_regression_StaticInstanceAndMethod_test2 94
#define M_thinj_regression_SystemTimeTest_main_Ljava_lang_String 74
#define M_thinj_regression_ThreadTest__clinit 28
#define M_thinj_regression_ThreadTest_main_Ljava_lang_String 74
#define M_thinj_regression_ThreadTest_test3 106
#define M_thinj_regression_ThreadTest_test4 112
#define M_thinj_regression_ThreadTest_test5 113
#define M_thinj_regression_ThreadTest_test6 114
#define M_thinj_regression_ThreadTest_test7 115
#define M_thinj_regression_ThreadTest_test8 180
#define M_thinj_regression_ThreadTest_test9 181
#define M_thinj_regression_ThreadTest_test10 183
#define M_thinj_regression_ThreadTest_test11 184
#define M_thinj_regression_ThreadTest_test12 185
#define M_thinj_regression_ThreadTest_busyWaitJ 209
#define M_thinj_regression_ThreadTest_simpleYield 213
#define M_thinj_regression_ThreadTest_yieldAndGC 214
#define M_thinj_regression_ThreadTest_testAutoYield 215
#define M_thinj_regression_ThreadTest_threadGC 216
#define M_thinj_regression_ThreadTest_testExplicitYield 217
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_0 218
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_2 219
#define M_thinj_regression_ThreadTest_testMonitorEnterExit_1 220
#define M_thinj_regression_ThreadTest_test2_1 221
#define M_thinj_regression_ThreadTest_test2_2 222
#define M_thinj_regression_ThreadTest_test2_3 223
#define M_thinj_regression_ThreadTest_test2_4 224
#define M_thinj_regression_ThreadTest_busyWaitDoneJ 225
#define M_thinj_regression_ThreadTest_test9_helper1 228
#define M_thinj_regression_ThreadTest_test9_helper2 229
#define M_thinj_regression_ThreadTest_access_008 230
#define M_thinj_regression_ThreadTest_access_102Z 231
#define M_thinj_regression_ThreadTest_access_200 232
#define M_thinj_regression_ThreadTest_access_300J 233
#define M_thinj_regression_ThreadTest_access_202Z 234
#define M_thinj_regression_ThreadTest_access_000 235
#define M_thinj_regression_ThreadTest_access_100 236
#define M_thinj_regression_ThreadTest_access_400 237
#define M_thinj_regression_ThreadTest_access_508 238
#define M_thinj_regression_ThreadTest_1__init 1
#define M_thinj_regression_ThreadTest_1_run 44
#define M_thinj_regression_ThreadTest_10__init 1
#define M_thinj_regression_ThreadTest_10_run 44
#define M_thinj_regression_ThreadTest_11__init 1
#define M_thinj_regression_ThreadTest_11_run 44
#define M_thinj_regression_ThreadTest_12__init 1
#define M_thinj_regression_ThreadTest_12_run 44
#define M_thinj_regression_ThreadTest_13__init 1
#define M_thinj_regression_ThreadTest_13_run 44
#define M_thinj_regression_ThreadTest_14__init 1
#define M_thinj_regression_ThreadTest_14_run 44
#define M_thinj_regression_ThreadTest_15__init 1
#define M_thinj_regression_ThreadTest_15_run 44
#define M_thinj_regression_ThreadTest_16__init 1
#define M_thinj_regression_ThreadTest_16_run 44
#define M_thinj_regression_ThreadTest_17__init 1
#define M_thinj_regression_ThreadTest_17_run 44
#define M_thinj_regression_ThreadTest_18__init 1
#define M_thinj_regression_ThreadTest_18_run 44
#define M_thinj_regression_ThreadTest_19__init 1
#define M_thinj_regression_ThreadTest_19_run 44
#define M_thinj_regression_ThreadTest_2__init 1
#define M_thinj_regression_ThreadTest_2_run 44
#define M_thinj_regression_ThreadTest_20__init 1
#define M_thinj_regression_ThreadTest_20_run 44
#define M_thinj_regression_ThreadTest_3__init 1
#define M_thinj_regression_ThreadTest_3_run 44
#define M_thinj_regression_ThreadTest_4_run 44
#define M_thinj_regression_ThreadTest_4__init_Ljava_lang_Object 226
#define M_thinj_regression_ThreadTest_5_run 44
#define M_thinj_regression_ThreadTest_5__init_Ljava_lang_Object_Ljava_lang_Thread 227
#define M_thinj_regression_ThreadTest_6_run 44
#define M_thinj_regression_ThreadTest_6__init_Ljava_lang_Object 226
#define M_thinj_regression_ThreadTest_7__init 1
#define M_thinj_regression_ThreadTest_7_run 44
#define M_thinj_regression_ThreadTest_8_run 44
#define M_thinj_regression_ThreadTest_8__init_Ljava_lang_Object 226
#define M_thinj_regression_ThreadTest_9_run 44
#define M_thinj_regression_ThreadTest_9__init_Ljava_lang_Object 226
#define M_thinj_regression_abstractclass_AbstractClass__init_I 25
#define M_thinj_regression_abstractclass_AbstractClass_main 73
#define M_thinj_regression_abstractclass_AbstractClass_test1 93
#define M_thinj_regression_abstractclass_AbstractClass_test2 105
#define M_thinj_regression_abstractclass_AbstractClass_foobar 116
#define M_thinj_regression_abstractclass_ExtendingClass__init_I 25
#define M_thinj_regression_abstractclass_ExtendingClass_foobar 116
#define M_thinj_regression_arrays_ArrayTest__init 1
#define M_thinj_regression_arrays_ArrayTest_main 73
#define M_thinj_regression_arrays_ArrayTest_test1 93
#define M_thinj_regression_arrays_ArrayTest_test2 105
#define M_thinj_regression_arrays_DummyClass__clinit 28
#define M_thinj_regression_arrays_DummyClass_cyclicDependency 123
#define M_thinj_regression_arrays_MultiArrayTest__clinit 28
#define M_thinj_regression_arrays_MultiArrayTest_main 73
#define M_thinj_regression_arrays_MultiArrayTest_test1 93
#define M_thinj_regression_arrays_MultiArrayTest_test2 105
#define M_thinj_regression_arrays_MultiArrayTest_test3 106
#define M_thinj_regression_arrays_Sudoku__clinit 28
#define M_thinj_regression_arrays_Sudoku_main 73
#define M_thinj_regression_arrays_Sudoku_solve__II 127
#define M_thinj_regression_arrays_Sudoku_getUsedValues__III 128
#define M_thinj_regression_checkcast_CheckCast_main 73
#define M_thinj_regression_checkcast_CheckCast_test1 93
#define M_thinj_regression_checkcast_CheckCast_test2 105
#define M_thinj_regression_checkcast_CheckCast_test3 106
#define M_thinj_regression_checkcast_CheckCast_test4 112
#define M_thinj_regression_checkcast_CheckCast_multitestLjava_lang_Object 139
#define M_thinj_regression_checkcast_CheckCast_1__init 1
#define M_thinj_regression_checkcast_CheckCast_ClassA__init 1
#define M_thinj_regression_checkcast_CheckCast_ClassB__init 1
#define M_thinj_regression_exceptions_ExIALOAD_main 73
#define M_thinj_regression_exceptions_ExIALOAD_get 119
#define M_thinj_regression_exceptions_ExIALOAD_getI 155
#define M_thinj_regression_exceptions_ExIALOAD_iaload 157
#define M_thinj_regression_exceptions_ExIALOAD_aaload 158
#define M_thinj_regression_exceptions_ExIALOAD_baload 159
#define M_thinj_regression_exceptions_ExIALOAD_caload 160
#define M_thinj_regression_exceptions_ExIALOAD_iastore 161
#define M_thinj_regression_exceptions_ExIALOAD_aastore 162
#define M_thinj_regression_exceptions_ExIALOAD_bastore 163
#define M_thinj_regression_exceptions_ExIALOAD_castore 164
#define M_thinj_regression_exceptions_ExIALOAD_idiv 165
#define M_thinj_regression_exceptions_ExIALOAD_irem 166
#define M_thinj_regression_exceptions_ExIALOAD_getfield 167
#define M_thinj_regression_exceptions_ExIALOAD_putfield 168
#define M_thinj_regression_exceptions_ExIALOAD_invokespecial 169
#define M_thinj_regression_exceptions_ExIALOAD_invokevirtual 170
#define M_thinj_regression_exceptions_ExIALOAD_invokeinterface 171
#define M_thinj_regression_exceptions_ExIALOAD_test_new 172
#define M_thinj_regression_exceptions_ExIALOAD_newarray 173
#define M_thinj_regression_exceptions_ExIALOAD_anewarray 174
#define M_thinj_regression_exceptions_ExIALOAD_arraylength 175
#define M_thinj_regression_exceptions_ExIALOAD_athrow 176
#define M_thinj_regression_exceptions_ExIALOAD_checkcast 177
#define M_thinj_regression_exceptions_ExIALOAD_LinkObject_consumeHeapI 156
#define M_thinj_regression_exceptions_ExIALOAD_LinkObject__init_Lthinj_regression_exceptions_ExIALOAD_LinkObject_I 179
#define M_thinj_regression_exceptions_ExIALOAD_MyInterface_foobar 116
#define M_thinj_regression_exceptions_ExceptionProxying_testExceptionProxy 146
#define M_thinj_regression_exceptions_TestNullPointerException_main 73
#define M_thinj_regression_exceptions_TestNullPointerException_test1 93
#define M_thinj_regression_exceptions_TestNullPointerException_test2 105
#define M_thinj_regression_exceptions_ThrowException_main 73
#define M_thinj_regression_exceptions_ThrowException_test1 93
#define M_thinj_regression_exceptions_ThrowException_test2 105
#define M_thinj_regression_exceptions_ThrowException_test3 106
#define M_thinj_regression_exceptions_ThrowException_test4 112
#define M_thinj_regression_exceptions_ThrowException_test5 113
#define M_thinj_regression_exceptions_ThrowException_test6 114
#define M_thinj_regression_exceptions_ThrowException_test7 115
#define M_thinj_regression_exceptions_ThrowException_testHelper 145
#define M_thinj_regression_exceptions_ThrowException_test6Helper 148
#define M_thinj_regression_exceptions_ThrowException_test7Helper2 151
#define M_thinj_regression_exceptions_ThrowException_test7Helper1 152
#define M_thinj_regression_gc_GC_main 73
#define M_thinj_regression_gc_GC_circularObjects 131
#define M_thinj_regression_gc_GC_LinkObject__init_I 25
#define M_thinj_regression_gc_GC_LinkObject_access_002Lthinj_regression_gc_GC_LinkObject_Lthinj_regression_gc_GC_LinkObject 129
#define M_thinj_regression_gc_GC_LinkObject_access_000Lthinj_regression_gc_GC_LinkObject 130
#define M_thinj_regression_gc_HeapTest_main 73
#define M_thinj_regression_gc_HeapTest_test1 93
#define M_thinj_regression_gc_HeapTest_test2 105
#define M_thinj_regression_gc_HeapTest_test0 138
#define M_thinj_regression_interfaces_AnInterface_foobar 116
#define M_thinj_regression_interfaces_AnInterface_get 119
#define M_thinj_regression_interfaces_AnInterfaceImpl__init 1
#define M_thinj_regression_interfaces_AnInterfaceImpl_main 73
#define M_thinj_regression_interfaces_AnInterfaceImpl_test1 93
#define M_thinj_regression_interfaces_AnInterfaceImpl_foobar 116
#define M_thinj_regression_interfaces_AnInterfaceImpl_getLost 117
#define M_thinj_regression_interfaces_AnInterfaceImpl_get 119
#define M_thinj_regression_interfaces_AnotherInterface_getLost 117
